import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    paddingVertical: 20,
    flex: 1,
  },
  containerIItem: {
    flexDirection: "row",
    height: 80,
    borderBottomColor: "#AEAEB2",
    borderBottomWidth: 1,
    gap: 8,
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
  },
  infoContainer: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  imageContainer: {
    width: 48,
    height: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#D1D1D6",
    overflow: "hidden",
    backgroundColor: "#007AFF",
    justifyContent: "center",
    alignItems: "center",
  },
  nameInitials: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "Nunito_900Black",
  },
  image: {
    width: "100%",
    height: "100%",
  },
  name: {
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 24,
    color: "#1C0335",
    fontFamily: "Nunito_700Bold",
  },
  email: {
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 20,
    color: "#1C0335",
    fontFamily: "Nunito_300Light",
  },
  rightActionContainer: {
    justifyContent: "center",
    alignItems: "flex-end",
    width: 96,
    // keep same height as card padding (~112)
    paddingVertical: 8,
  },
  rightAction: {
    backgroundColor: "#FF3B30",
    width: 60,
    height: 80,
    borderRadius: 7,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  rightActionIcon: {
    width: 16,
    height: 16,
    tintColor: "#FFFFFF",
    marginBottom: 10,
  },
  rightActionText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontFamily: "Nunito_700Bold",
  },
  searchContainer: {
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  titleAndCountContainer: {
    paddingHorizontal: 16,
    paddingVertical: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  title: {
    fontSize: 18,
    fontFamily: "Nunito_700Bold",
    color: "#1A0034",
  },
  countContainer: {
    backgroundColor: "#00A0FF",
    borderRadius: 100,
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  count: {
    color: "#FFFFFF",
    fontSize: 11,
    fontFamily: "Nunito_700Bold",
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: 16,
  },
  containerWithKeyboard: {
    paddingTop: 150,
  },
  statusAccepted: {
    justifyContent: "center",
    alignItems: "center",
    height: 24,
    width: 69,
    borderColor: "#330065",
    borderWidth: 1,
    borderRadius: 16.75,
  },
  statusAcceptedText: {
    fontSize: 9,
    color: "#330065",
    fontFamily: "Nunito_600SemiBold",
  },
  statusSent: {
    justifyContent: "center",
    alignItems: "center",
    height: 24,
    width: 69,
    backgroundColor: "#8E8E93",
    borderRadius: 16.75,
  },
  statusSentText: {
    fontSize: 9,
    color: "#FFFFFF",
    fontFamily: "Nunito_600SemiBold",
  },
  statusRespond: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#E6F4FF",
    borderRadius: 6,
  },
  statusRespondText: {
    fontSize: 12,
    color: "#1890FF",
    fontFamily: "Nunito_600SemiBold",
  },
});
