export type PersonaChoice = "giftee" | "gifter" | "both";

export const GENDER_OPTIONS = ["Female", "Male"];

export const PERSONA_OPTIONS: {
  id: PersonaChoice;
  title: string;
  description: string;
}[] = [
  {
    id: "giftee",
    title: "I'm creating my wishlists",
    description: "Plan events, add gifts, and share lists so friends know what to buy.",
  },
  {
    id: "gifter",
    title: "I'm shopping for others",
    description: "Claim gifts from shared lists and keep purchases organised.",
  },
  {
    id: "both",
    title: "I do a bit of both",
    description: "Swap between making lists for yourself and buying for loved ones.",
  },
];

export const OCCASION_OPTIONS = ["Birthday", "Anniversary", "Baby shower", "Wedding", "Graduation", "Holiday gifting"];

export const GIFT_INTEREST_OPTIONS = ["Tech & Gadgets", "Home & Living", "Fashion & Accessories", "Beauty & Wellness", "Experiences", "Books & Stationery", "Kids & Family", "Food & Gourmet"];

export const SHOPPING_STYLE_OPTIONS = ["I love curated picks", "Show me trending now", "Let me browse everything"];

export const BUDGET_RANGE_OPTIONS = ["Under AED 150", "AED 150 – 350", "AED 350 – 750", "AED 750+"];

export const DISCOVERY_CHANNEL_OPTIONS = ["Instagram", "TikTok", "Pinterest", "YouTube", "Newsletters", "Friends & family", "In-store browsing"];

export const STORE_SUGGESTIONS = ["Amazon.ae", "Namshi", "Bloomingdale's", "Level Shoes", "Pottery Barn", "Crate & Barrel", "Ounass", "Virgin Megastore"];

export const SECONDARY_PURPLE = "#4B0082";

export const COUNTRY_OPTIONS = [
  "United Arab Emirates",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
