import { StyleSheet } from "react-native";

export const desktopStyles = StyleSheet.create({
  shareModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  shareModal: {
    width: "100%",
    maxWidth: 920,
    maxHeight: "95%",
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    padding: 32,
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  shareModalTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  shareModalTitle: {
    fontSize: 24,
    fontFamily: "Nunito_700Bold",
    color: "#220044",
  },
  shareModalBody: {
    flexDirection: "row",
    gap: 32,
  },
  shareModalColumn: {
    flex: 1,
  },
  shareModalSubtitle: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#220044",
    marginVertical: 16,
  },
  shareModalSearchBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: "#AEAEB2",
    borderRadius: 100,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 20,
    backgroundColor: "#ffff",
    outline: "none",
  },
  shareModalSearchInput: {
    flex: 1,
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#1C0335",
    borderWidth: 0,
    outlineColor: "transparent",
  },
  shareModalGroupGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
  },
  headingSection: {
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  headingItem: {
    flexDirection: "row",
    gap: 8,
  },
  heading: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
  },
  headingCountWrap: {
    width: 24,
    height: 24,
    padding: 6,
    borderRadius: "100%",
    backgroundColor: "#220044",
    alignItems: "center",
    justifyContent: "center",
  },
  headingCount: {
    color: "#FFFFFF",
    fontFamily: "Nunito_700Bold",
    fontSize: 14,
    textAlign: "center",
  },
  selectedText: {
    fontSize: 16,
    color: "#220044",
    fontFamily: "Nunito_400Regular",
  },
  selectedCount: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
    color: "#220044",
  },
  shareModalGroupCard: {
    width: 140,
    position: "relative",
    borderRadius: 8,
    overflow: "hidden",
    height: 120,
    backgroundColor: "#C9B7F5",
    padding: 12,
    justifyContent: "space-between",
    // borderWidth: 2,
    // borderColor: "#ffff",
  },
  shareModalGroupSelected: {
    // borderWidth: 2,
    // borderColor: "#4B0082",
  },
  shareModalGroupCheck: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 15,
    height: 15,
    borderRadius: 2,
    borderColor: "#FFFFFF",
    borderWidth: 1.5,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  shareModalGroupCheckSelected: {
    backgroundColor: "#FFFFFF",
  },
  shareModalGroupText: {
    // position: "absolute",
    // left: 16,
    // bottom: 16,
  },
  shareModalGroupTitle: {
    fontSize: 14,
    fontFamily: "Nunito_900Black",
    color: "#FFFFFF",
  },
  shareModalGroupBy: {
    fontSize: 10.32,
    fontFamily: "Nunito_400Regular",
    color: "#FFFFFF",
  },
  shareModalGroupByHighlight: {
    fontFamily: "Nunito_700Bold",
  },
  groupImage: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#845EF7",
  },
  groupOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(28, 3, 53, 0.65)",
  },
  groupCheck: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    borderColor: "#FFFFFF",
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  shareModalFriendRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    // paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#AEAEB2",
    flex: 1,
  },
  shareModalFriendAvatar: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: "#E4E4FF",
    alignItems: "center",
    justifyContent: "center",
  },
  shareModalFriendInitials: {
    fontSize: 16,
    fontFamily: "Nunito_900Black",
    color: "#3B0076",
  },
  shareModalFriendName: {
    fontSize: 16,
    fontFamily: "Nunito_600SemiBold",
    color: "#1C0335",
  },
  shareModalFriendEmail: {
    fontSize: 12,
    fontFamily: "Nunito_400Regular",
    color: "#6B5C87",
  },
  shareModalFriendCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#AEAEB2",
    alignItems: "center",
    justifyContent: "center",
  },
  shareModalFriendCheckboxSelected: {
    backgroundColor: "#4B0082",
    borderColor: "#4B0082",
  },
  shareModalFooter: {
    marginTop: 24,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 16,
  },
  desktopSecondaryButton: {
    paddingHorizontal: 28,
    justifyContent: "center",
    alignItems: "center",
    height: 48,
    minWidth: 98,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#330065",
    backgroundColor: "#FFFFFF",
  },
  desktopSecondaryButtonText: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#330065",
  },
  desktopPrimaryButton: {
    justifyContent: "center",
    alignItems: "center",
    height: 48,
    minWidth: 88,
    paddingHorizontal: 32,
    borderRadius: 8,
    backgroundColor: "#330065",
  },
  desktopPrimaryButtonText: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#FFFFFF",
  },
});
export const styles = StyleSheet.create({});
