
import { Dimensions, StyleSheet } from "react-native";

const { width: screenWidth } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    paddingBottom: 16,
  },
  headerContent: {
    paddingHorizontal: 16,
    paddingTop: 50,
  },
  navigation: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
    lineHeight: 28,
    letterSpacing: -1,
  },
  progressContainer: {
    paddingHorizontal: 16,
    paddingVertical: 40,
    alignItems: "center",
  },
  progressBarContainer: {
    flexDirection: "row",
    width: screenWidth - 32,
    gap: 4,
  },
  progressSegment: {
    flex: 1,
    height: 8,
    borderRadius: 4,
  },
  progressActive: {
    backgroundColor: "#45018A",
  },
  progressInactive: {
    backgroundColor: "#DDD7E4",
  },
  contentScroll: {
    paddingHorizontal: 16,
    // Leave room for the fixed footer so content isn't hidden
    paddingBottom: 140,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
    marginBottom: 24,
    lineHeight: 28,
  },
  optionsContainer: {
    gap: 16,
  },
  optionCard: {
    borderRadius: 8,
    borderWidth: 1,
    padding: 16,
    minHeight: 171,
  },
  optionCardSelected: {
    borderColor: "#1C0335",
  },
  optionCardSelectedBackground: {
    backgroundColor: "#F5EDFE",
  },
  optionCardUnselected: {
    borderColor: "#AEAEB2",
  },
  optionContent: {
    position: "relative",
  },
  checkboxContainer: {
    position: "absolute",
    right: 0,
    top: 0,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxSelected: {
    backgroundColor: "#3B0076",
  },
  checkboxUnselected: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#AEAEB2",
  },
  optionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
    marginTop: 24,
  },
  optionTitle: {
    fontSize: 24,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
    lineHeight: 24,
  },
  optionDescription: {
    fontSize: 16,
    fontWeight: "400",
    fontFamily: "Nunito_400Regular",
    color: "#1C0335",
    lineHeight: 24,
    marginRight: 24,
  },
  publicExtra: {
    marginTop: 12,
    gap: 12,
  },
  passwordRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  passwordLabel: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  passwordInputWrapper: {
    borderWidth: 1,
    borderColor: "#AEAEB2",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  passwordInput: {
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#1C0335",
  },
  passwordHint: {
    fontSize: 12,
    fontFamily: "Nunito_300Light",
    color: "#8E8E93",
    marginTop: 4,
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    gap: 16,
    borderTopWidth: 1,
    borderTopColor: '#E5E5EA',
    zIndex: 1000,
  },
  button: {
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: "center",
  },
  buttonPrimary: {
    backgroundColor: "#3B0076",
  },
  buttonDisabled: {
    backgroundColor: "#D1D1D6",
  },
  buttonSecondary: {
    borderWidth: 1,
    borderColor: "#3B0076",
  },
  buttonPrimaryText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
  },
  buttonSecondaryText: {
    color: "#3B0076",
    fontSize: 16,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
  },
  sheetBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  sheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: Dimensions.get("window").height * 0.9,
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 48,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#DDD7E4",
    marginBottom: 12,
  },
  sheetTitle: {
    fontSize: 24,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
    marginBottom: 16,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#AEAEB2",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 16,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#1C0335",
  },
  groupGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    justifyContent: "space-between",
  },
  groupCard: {
    width: (Dimensions.get("window").width - 16 * 2 - 12) / 2,
    height: 140,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#C9B7F5",
    position: "relative",
  },
  groupCardSelected: {
    borderWidth: 2,
    borderColor: "#3B0076",
  },
  groupImage: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#845EF7",
  },
  groupOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(28,3,53,0.35)",
  },
  groupCheck: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  groupCheckSelected: {
    backgroundColor: "#3B0076",
  },
  groupTextWrap: {
    position: "absolute",
    left: 12,
    bottom: 12,
  },
  groupTitle: {
    fontSize: 18,
    fontWeight: "800",
    fontFamily: "Nunito_700Bold",
    color: "#FFFFFF",
  },
  groupBy: {
    fontSize: 12,
    fontFamily: "Nunito_400Regular",
    color: "#FFFFFF",
  },
  orWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginVertical: 12,
  },
  orLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#DDD7E4",
  },
  orText: {
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  shareWithFriends: {
    fontSize: 24,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
    marginBottom: 8,
  },
  friendList: {
    borderTopWidth: 1,
    borderTopColor: "#E5E5EA",
  },
  friendRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5EA",
  },
  avatarCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#E4E4FF",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitials: {
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
  },
  friendName: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  friendEmail: {
    fontSize: 12,
    fontFamily: "Nunito_300Light",
    color: "#8E8E93",
  },
  friendCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#AEAEB2",
    alignItems: "center",
    justifyContent: "center",
  },
  friendCheckboxSelected: {
    backgroundColor: "#3B0076",
    borderColor: "#3B0076",
  },
});

export const desktopStyles = StyleSheet.create({
  desktopSafeArea: {
    flex: 1,
    backgroundColor: "#F8F5FF",
  },
  desktopWrapper: {
    flex: 1,
    flexDirection: "row",
  },
  desktopSidebar: {
    width: 320,
    paddingVertical: 56,
    paddingHorizontal: 48,
    backgroundColor: "#FBF8FF",
    borderRightWidth: 1,
    borderRightColor: "#E7DCF6",
  },
  desktopBackLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 32,
  },
  desktopBackText: {
    fontSize: 16,
    fontFamily: "Nunito_600SemiBold",
    color: "#4B0082",
  },
  desktopTitle: {
    fontSize: 32,
    fontFamily: "Nunito_700Bold",
    color: "#330065",
    marginBottom: 12,
  },
  desktopSubtitle: {
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#4A3B66",
    lineHeight: 24,
    marginBottom: 40,
  },
  desktopStepList: {
    gap: 24,
  },
  desktopStepItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 16,
  },
  desktopStepIndicator: {
    alignItems: "center",
    position: "relative",
  },
  desktopStepCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#D8C9F6",
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
  },
  desktopStepCircleComplete: {
    backgroundColor: "#4B0082",
    borderColor: "#4B0082",
  },
  desktopStepCircleCurrent: {
    borderColor: "#4B0082",
    backgroundColor: "#F5EDFF",
  },
  desktopStepNumber: {
    fontSize: 18,
    fontFamily: "Nunito_700Bold",
  },
  desktopStepNumberActive: {
    color: "#4B0082",
  },
  desktopStepNumberInactive: {
    color: "#8E8EA9",
  },
  desktopStepConnector: {
    position: "absolute",
    top: 44,
    left: 19,
    width: 2,
    height: 48,
    backgroundColor: "#E7DCF6",
  },
  desktopStepLabel: {
    fontSize: 18,
    fontFamily: "Nunito_600SemiBold",
    color: "#8E8EA9",
    flex: 1,
  },
  desktopStepLabelActive: {
    color: "#330065",
  },
  desktopStepLabelComplete: {
    color: "#4B0082",
  },
  desktopContentScroll: {
    flexGrow: 1,
    paddingVertical: 56,
    paddingHorizontal: 64,
  },
  desktopContent: {
    flex: 1,
    gap: 32,
  },
  desktopHeadingBlock: {
    gap: 12,
  },
  desktopSectionHeading: {
    fontSize: 28,
    fontFamily: "Nunito_700Bold",
    color: "#330065",
  },
  desktopSectionDescription: {
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#4A3B66",
    lineHeight: 24,
  },
  desktopOptionStack: {
    gap: 16,
  },
  desktopOptionCard: {
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#D8C9F6",
    backgroundColor: "#FFFFFF",
    padding: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 24,
  },
  desktopOptionCardSelected: {
    borderColor: "#4B0082",
    backgroundColor: "#F5EDFF",
    shadowColor: "#4B0082",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  desktopOptionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    flex: 1,
  },
  desktopOptionIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#EDE4FF",
    alignItems: "center",
    justifyContent: "center",
  },
  desktopOptionTextWrap: {
    flex: 1,
    gap: 6,
  },
  desktopOptionTitle: {
    fontSize: 22,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  desktopOptionDescription: {
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#3E2D61",
    lineHeight: 22,
  },
  desktopInfoIcon: {
    marginLeft: 8,
  },
  desktopRadio: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#D8C9F6",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  desktopRadioSelected: {
    borderColor: "#4B0082",
  },
  desktopRadioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#4B0082",
  },
  desktopPublicExtras: {
    marginTop: 20,
    padding: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D8C9F6",
    backgroundColor: "#FFFFFF",
    gap: 16,
  },
  desktopPasswordRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  desktopPasswordLabel: {
    fontSize: 18,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  desktopPasswordInputWrapper: {
    gap: 8,
  },
  desktopPasswordInput: {
    borderWidth: 1,
    borderColor: "#D8C9F6",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#1C0335",
    backgroundColor: "#FBF8FF",
  },
  desktopPasswordHint: {
    fontSize: 13,
    fontFamily: "Nunito_400Regular",
    color: "#6B5C87",
  },
  desktopActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 16,
    marginTop: 24,
  },
  desktopSecondaryButton: {
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#4B0082",
    backgroundColor: "#FFFFFF",
  },
  desktopSecondaryButtonText: {
    fontSize: 16,
    fontFamily: "Nunito_600SemiBold",
    color: "#4B0082",
  },
  desktopPrimaryButton: {
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 10,
    backgroundColor: "#4B0082",
  },
  desktopPrimaryButtonDisabled: {
    backgroundColor: "#CDB8EC",
  },
  desktopPrimaryButtonText: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#FFFFFF",
  },
  shareModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  shareModal: {
    width: "100%",
    maxWidth: 920,
    maxHeight: "90%",
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    padding: 32,
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  shareModalTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  shareModalTitle: {
    fontSize: 28,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  shareModalBody: {
    flexDirection: "row",
    gap: 32,
  },
  shareModalColumn: {
    flex: 1,
  },
  shareModalSubtitle: {
    fontSize: 18,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
    marginBottom: 16,
  },
  shareModalSearchBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: "#D8C9F6",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 20,
    backgroundColor: "#FBF8FF",
  },
  shareModalSearchInput: {
    flex: 1,
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#1C0335",
  },
  shareModalGroupGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
  },
  shareModalGroupCard: {
    width: "48%",
    position: "relative",
    borderRadius: 16,
    overflow: "hidden",
    height: 160,
    backgroundColor: "#C9B7F5",
  },
  shareModalGroupSelected: {
    borderWidth: 2,
    borderColor: "#4B0082",
  },
  shareModalGroupCheck: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  shareModalGroupCheckSelected: {
    backgroundColor: "#4B0082",
  },
  shareModalGroupText: {
    position: "absolute",
    left: 16,
    bottom: 16,
  },
  shareModalGroupTitle: {
    fontSize: 20,
    fontFamily: "Nunito_700Bold",
    color: "#FFFFFF",
  },
  shareModalGroupBy: {
    fontSize: 13,
    fontFamily: "Nunito_400Regular",
    color: "#FFFFFF",
  },
  shareModalSeparator: {
    width: 1,
    backgroundColor: "#E7DCF6",
  },
  shareModalFriendList: {
    borderWidth: 1,
    borderColor: "#E7DCF6",
    borderRadius: 16,
    overflow: "hidden",
  },
  shareModalFriendRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E7DCF6",
  },
  shareModalFriendAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#E4E4FF",
    alignItems: "center",
    justifyContent: "center",
  },
  shareModalFriendInitials: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
  },
  shareModalFriendName: {
    fontSize: 16,
    fontFamily: "Nunito_600SemiBold",
    color: "#1C0335",
  },
  shareModalFriendEmail: {
    fontSize: 12,
    fontFamily: "Nunito_400Regular",
    color: "#6B5C87",
  },
  shareModalFriendCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#AEAEB2",
    alignItems: "center",
    justifyContent: "center",
  },
  shareModalFriendCheckboxSelected: {
    backgroundColor: "#4B0082",
    borderColor: "#4B0082",
  },
  shareModalFooter: {
    marginTop: 24,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 16,
  },
});
