import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {},
  inputWrapper: {
    height: 56,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#AEAEB2",
    position: "relative",
  },
  input: {
    flex: 1,
    fontSize: 16,
    height: "100%",
    padding: 16,
    fontFamily: "Nunito_400Regular",
    color: "#1C0335",
    lineHeight: 24,
  },
  labelContainer: {
    position: "absolute",
    backgroundColor: "#ffff",
    paddingHorizontal: 8,
    paddingVertical: 4,
    top: -18,
    marginLeft: 13,
  },
  label: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  rightIconContainer: {
    position: "absolute",
    right: 0,
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
    minWidth: 50,
  },
  dropdownContainer: {
    position: "absolute",
    top: 60,
    left: 0,
    right: 0,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E4DBF6",
    shadowColor: "#2A174C",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
    zIndex: 60,
  },
  backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.3)" },
  sheetHandle: { alignSelf: "center", width: 60, height: 6, borderRadius: 3, backgroundColor: "#C8C7CC", marginTop: 8, marginBottom: 16 },
  sheetContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    maxHeight: "50%",
    backgroundColor: "#ffff",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingBottom: 40,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: -4 },
    shadowRadius: 12,
    elevation: 8,
    overflow: "hidden",
  },
  sortSheetTitle: { fontSize: 24, fontFamily: "Nunito_700Bold", color: "#1C0335", textAlign: "center", marginTop: 4 },

  sheetContent: { flex: 1, paddingHorizontal: 16, paddingBottom: 60, gap: 10 },

  dropdownItem: {},
  dropdownItemText: {
    color: "#1C0335",
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
  },
  didYouBuyThisGiftSeparator: {
    borderBottomWidth: 0.5,
    borderBottomColor: "#808080",
    marginVertical: 5,
  },

  errorText: { fontSize: 12, color: "#B00020", fontFamily: "Nunito_700Bold" },
});
