import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    paddingBottom: 16,
  },
  headerContent: {
    paddingHorizontal: 16,
    paddingTop: 50,
  },
  navigation: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
    lineHeight: 28,
    letterSpacing: -1,
  },
  scrollContent: {
    paddingBottom: 200, // Space for footer
  },
  coverContainer: {
    height: 145,
    width: "100%",
  },
  coverImage: {
    height: "100%",
    width: "100%",
    resizeMode: "cover",
  },
  coverOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(29, 23, 0, 0.32)",
    justifyContent: "center",
    alignItems: "center",
  },
  daysToGo: {
    color: "#FFFFFF",
    fontSize: 40,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
    textShadowColor: "rgba(0, 0, 0, 0.25)",
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 40,
  },
  listInfoContainer: {
    marginTop: -40,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  actionsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#AEAEB2",
  },
  privacyContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  privacyStatus: {
    fontSize: 16,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  privacyDesc: {
    fontSize: 12,
    fontFamily: "Nunito_300Light",
    color: "#1C0335",
  },
  actionButtons: {
    flexDirection: "row",
    gap: 8,
  },
  iconButton: {
    borderWidth: 1,
    borderColor: "#1C0335",
    borderRadius: 20,
    padding: 8,
  },
  addGiftSection: {
    paddingHorizontal: 16,
    paddingVertical: 24,
    gap: 16,
  },
  addGiftTitle: { fontSize: 16, fontFamily: 'Nunito_700Bold', color: '#1C0335' },
  addGiftButton: { height: 134, borderWidth: 1, borderColor: '#AEAEB2', borderStyle: 'dashed', borderRadius: 8, justifyContent: 'center', alignItems: 'center', flexDirection: 'row', gap: 8 },
  addGiftButtonText: { fontSize: 16, fontFamily: 'Nunito_700Bold', color: '#3B0076' },
  itemCard: {
    flexDirection: 'row',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E5EA',
    borderRadius: 12,
    gap: 16,
  },
  itemImageWrap: { width: 96, height: 96, borderRadius: 12, overflow: 'hidden', borderWidth: 1, borderColor: '#E5E5EA', justifyContent: 'center', alignItems: 'center' },
  itemImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  itemContent: { flex: 1 },
  itemName: { fontSize: 16, fontFamily: 'Nunito_700Bold', color: '#1C0335', marginBottom: 4 },
  itemQuantity: { fontSize: 12, fontFamily: 'Nunito_400Regular', color: '#1C0335', marginBottom: 4 },
  itemQuantityValue: { fontFamily: 'Nunito_700Bold' },
  claimBadgeWrap: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 },
  claimBadge: { backgroundColor: '#F9E2A7', borderRadius: 6, paddingHorizontal: 8, paddingVertical: 4 },
  claimBadgeText: { fontSize: 12, fontFamily: 'Nunito_700Bold', color: '#784B00' },
  itemChevron: { padding: 4 },
  priceRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  itemPrice: { fontSize: 16, fontFamily: 'Nunito_700Bold', color: '#1C0335' },
  buyNow: { fontSize: 16, fontFamily: 'Nunito_700Bold', color: 'white', backgroundColor: '#0062FF', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6 },
  progressTrack: { height: 6, backgroundColor: '#D1D1D6', borderRadius: 3, overflow: 'hidden' },
  progressFill: { backgroundColor: '#3B0076', height: '100%' },
  infoBox: {
    backgroundColor: "#F5EDFE",
    borderRadius: 8,
    padding: 8,
    marginHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  infoText: {
    flex: 1,
    fontSize: 12,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
  },
  linkText: {
    textDecorationLine: "underline",
    color: "#0062FF",
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 34,
    gap: 16,
    borderTopWidth: 1,
    borderTopColor: "#D1D1D6",
  },
  lastUpdated: {
    textAlign: "center",
    fontSize: 12,
    fontFamily: "Nunito_300Light",
    color: "#1C0335",
  },
  button: {
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
  },
  buttonPrimary: {
    backgroundColor: "#3B0076",
  },
  buttonSecondary: {
    borderWidth: 1,
    borderColor: "#3B0076",
  },
  buttonPrimaryText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
  },
  buttonSecondaryText: {
    color: "#3B0076",
    fontSize: 16,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
  },
  // Bottom sheet styles
  backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.3)" },
  sheetContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    maxHeight: "92%",
    backgroundColor: "#F5F4F8",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingBottom: 40,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: -4 },
    shadowRadius: 12,
    elevation: 8,
  },
  sheetHandle: { alignSelf: "center", width: 60, height: 6, borderRadius: 3, backgroundColor: "#C8C7CC", marginTop: 8, marginBottom: 16 },
  sheetContent: { paddingHorizontal: 16, paddingBottom: 60, gap: 20 },
  sheetTitle: { fontSize: 28, fontWeight: "700", fontFamily: "Nunito_700Bold", color: "#1C0335", marginTop: 8 },
  fieldGroup: { gap: 8 },
  fieldLabel: { fontSize: 14, fontFamily: "Nunito_700Bold", color: "#1C0335" },
  inputRow: { flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: "#D1D1D6", backgroundColor: "#FFFFFF", borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, gap: 8 },
  input: { flex: 1, fontSize: 16, fontFamily: "Nunito_700Bold", color: "#1C0335", padding: 0 },
  orDivider: { flexDirection: "row", alignItems: "center", gap: 12 },
  orLine: { flex: 1, height: 1, backgroundColor: "#D1D1D6" },
  orText: { fontSize: 14, fontFamily: "Nunito_700Bold", color: "#1C0335" },
  qtyRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderWidth: 1, borderColor: "#D1D1D6", backgroundColor: "#F1EFF5", borderRadius: 12, paddingHorizontal: 12, paddingVertical: 14 },
  qtyBtn: { width: 48, height: 48, borderRadius: 8, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" },
  qtyBtnText: { fontSize: 28, color: "#1C0335", fontFamily: "Nunito_700Bold", lineHeight: 32 },
  qtyValue: { fontSize: 32, fontFamily: "Nunito_700Bold", color: "#1C0335" },
  textareaWrapper: { alignItems: "flex-start", paddingTop: 12 },
  textarea: { minHeight: 110, textAlignVertical: "top" },
  charCount: { position: "absolute", bottom: 8, right: 12, fontSize: 12, color: "#7A6F88", fontFamily: "Nunito_700Bold" },
  saveBtn: { height: 56, borderRadius: 12, backgroundColor: "#3B0076", alignItems: "center", justifyContent: "center" },
  saveBtnDisabled: { backgroundColor: "#D1D1D6" },
  saveBtnText: { fontSize: 18, fontFamily: "Nunito_700Bold", color: "#FFFFFF" },
  saveBtnTextDisabled: { color: "#8E8E93" },
  cancelBtn: { height: 56, borderRadius: 12, borderWidth: 1, borderColor: "#3B0076", backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" },
  cancelBtnText: { fontSize: 18, fontFamily: "Nunito_700Bold", color: "#3B0076" },
  scrapeStatus: { fontSize: 16, fontFamily: "Nunito_700Bold", color: "#7A6F88" },
  errorText: { fontSize: 12, color: "#B00020", fontFamily: "Nunito_700Bold" },
  previewImage: { width: 120, height: 120, borderRadius: 12, marginTop: 8, backgroundColor: '#E1DEE6' },
  addMoreButton: { marginTop: 8, alignSelf: 'center', flexDirection: 'row', gap: 6, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 24, borderWidth: 1, borderColor: '#3B0076', backgroundColor: '#FFFFFF' },
  addMoreButtonText: { fontSize: 14, fontFamily: 'Nunito_700Bold', color: '#3B0076' },
  // Legacy overlay (unused now) kept for reference
  browserOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: '#FFFFFF', elevation: 20 },
  browserHeader: { height: 56, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderBottomColor: '#E5E5EA', backgroundColor: '#F8F8FA' },
  browserHeaderBtn: { padding: 4 },
  browserTitle: { flex: 1, fontSize: 14, fontFamily: 'Nunito_700Bold', color: '#1C0335' },
  webview: { flex: 1 },
  browserAddBtn: { position: 'absolute', left: 16, right: 16, bottom: 32, backgroundColor: '#3B0076', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 16, borderRadius: 16, shadowColor: '#000', shadowOpacity: 0.25, shadowOffset: { width: 0, height: 4 }, shadowRadius: 12, elevation: 6 },
  browserAddBtnText: { color: '#FFFFFF', fontSize: 16, fontFamily: 'Nunito_700Bold' },
  browserModalContainer: { flex: 1, backgroundColor: '#FFFFFF' },
  browserActionBarWrapper: { paddingHorizontal: 16, paddingBottom: 16, backgroundColor: 'rgba(255,255,255,0.9)' },
  browserActionBar: { backgroundColor: '#3B0076', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 16, borderRadius: 12 },
  browserActionBarText: { color: '#FFFFFF', fontSize: 16, fontFamily: 'Nunito_700Bold' },
  // Sort & Filter sheet
  sortSheetContainer: { position: 'absolute', left: 0, right: 0, bottom: 0, backgroundColor: '#FFFFFF', borderTopLeftRadius: 32, borderTopRightRadius: 32, maxHeight: '80%' },
  sortSheetHandle: { width: 64, height: 6, borderRadius: 3, backgroundColor: '#C7C7CC', alignSelf: 'center', marginTop: 12 },
  sortSheetContent: { paddingBottom: 32, paddingHorizontal: 32, paddingTop: 8, gap: 24 },
  sortSheetTitle: { fontSize: 24, fontFamily: 'Nunito_700Bold', color: '#1C0335', textAlign: 'center', marginTop: 4 },
  sortDivider: { height: 1, backgroundColor: '#E5E5EA', marginTop: 16 },
  sortSection: { gap: 12 },
  sortSectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 8 },
  sortSectionTitle: { fontSize: 22, fontFamily: 'Nunito_700Bold', color: '#1C0335' },
  radioRow: { flexDirection: 'row', alignItems: 'center', gap: 18, paddingVertical: 8 },
  radioOuter: { width: 44, height: 44, borderRadius: 22, borderWidth: 2, borderColor: '#D5D2DA', alignItems: 'center', justifyContent: 'center' },
  radioOuterActive: { borderColor: '#360068', backgroundColor: 'rgba(54,0,104,0.08)' },
  radioInner: { width: 18, height: 18, borderRadius: 9, backgroundColor: '#360068' },
  radioLabel: { fontSize: 18, fontFamily: 'Nunito_600SemiBold', color: '#1C0335' },
  checkboxBox: { width: 44, height: 44, borderRadius: 22, borderWidth: 2, borderColor: '#D5D2DA', alignItems: 'center', justifyContent: 'center' },
  checkboxBoxActive: { borderColor: '#360068', backgroundColor: '#360068' },
  applyBarWrapper: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: 24, paddingTop: 16, paddingBottom: 24, backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#E5E5EA' },
  applyBtnFull: { backgroundColor: '#360068', height: 56, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  applyBtnText: { color: '#FFFFFF', fontSize: 18, fontFamily: 'Nunito_700Bold' },
  // Spacer at bottom of scroll so content not hidden behind apply bar
  sortScrollSpacer: { height: 120 },
});