import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    minHeight: 108,
    justifyContent: "flex-end",
  },
  headerContent: {
    paddingHorizontal: 16,
  },
  navigation: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    paddingVertical: 16,
  },
  backButton: {
    // padding: 4,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    fontFamily: "Nunito_700Bold",
    lineHeight: 28,
    letterSpacing: -1,
  },
  scrollContent: {
    paddingBottom: 260, // Extra space for footer + bottom tab bar on iOS
  },
  coverContainer: {
    height: 180,
    width: "100%",
    position: "relative",
  },
  coverImage: {
    height: "100%",
    width: "100%",
    resizeMode: "cover",
  },
  coverOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#1D170052",
    justifyContent: "center",
    alignItems: "center",
  },
  daysToGo: {
    color: "#FFFFFF",
    fontSize: 40,
    fontFamily: "Nunito_700Bold",
  },
  listInfoContainer: {
    marginTop: -40,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  actionsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  privacyContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  privacyStatus: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  privacyDesc: {
    fontSize: 12,
    fontFamily: "Nunito_300Light",
    color: "#1C0335",
  },
  actionButtons: {
    flexDirection: "row",
    gap: 8,
  },
  iconButton: {
    borderWidth: 1,
    borderColor: "#1C0335",
    borderRadius: 80,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  sectionSeparator: {
    height: 0.5,
    backgroundColor: "#AEAEB2",
    marginHorizontal: 16,
  },
  addGiftSection: {
    paddingBottom: 16,
    gap: 16,
  },
  addGiftTitle: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  addGiftButton: {
    height: 134,
    borderWidth: 1,
    borderColor: "#AEAEB2",
    borderStyle: "dashed",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  addGiftButtonText: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
  },
  itemCard: {
    flexDirection: "row",
    padding: 16,
    backgroundColor: "#FFFFFF",
    // borderWidth: 1,
    // borderColor: "#E5E5EA",
    // borderRadius: 12,
    gap: 16,
  },
  giftDivider: { height: 1, backgroundColor: "#D1D1D6" },
  itemImageWrap: {
    width: 93,
    height: 93,
    borderRadius: 8,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E5E5EA",
    justifyContent: "center",
    alignItems: "center",
  },
  itemImage: { width: "100%", height: "100%", resizeMode: "cover" },
  itemContent: { flex: 1 },
  itemName: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
    marginBottom: 4,
  },
  itemQuantity: {
    fontSize: 12,
    fontFamily: "Nunito_400Regular",
    color: "#1C0335",
    marginBottom: 4,
  },
  itemQuantityValue: { fontFamily: "Nunito_700Bold" },
  claimBadgeWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  claimBadge: {
    backgroundColor: "#F9E2A7",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  claimBadgeText: {
    fontSize: 12,
    fontFamily: "Nunito_700Bold",
    color: "#784B00",
  },
  // Grey variant for fully claimed items
  claimBadgeGrey: {
    backgroundColor: "#E5E5EA",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  claimBadgeGreyText: {
    fontSize: 12,
    fontFamily: "Nunito_700Bold",
    color: "#6B7280",
  },
  itemChevron: { padding: 4 },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  itemPrice: { fontSize: 16, fontFamily: "Nunito_700Bold", color: "#1C0335" },
  buyNow: {
    fontSize: 16,
    textDecorationLine: "underline",
    fontFamily: "Nunito_700Bold",
    color: "#0062FF",
    padding: 2,
  },
  buyNowDisabled: { backgroundColor: "#D1D1D6" },
  progressTrack: {
    height: 6,
    backgroundColor: "#D1D1D6",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressFill: { backgroundColor: "#3B0076", height: "100%" },
  // Swipe action styles
  rightActionContainer: {
    justifyContent: "center",
    alignItems: "flex-end",
    width: 96,
    // keep same height as card padding (~112)
    paddingVertical: 8,
  },
  rightAction: {
    backgroundColor: "#FF3B30",
    width: 110,
    height: "99%",
    borderRadius: 7,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  rightActionIcon: {
    tintColor: "#FFFFFF",
    marginBottom: 10,
  },
  rightActionText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
  },
  infoBox: {
    backgroundColor: "#F5EDFE",
    borderRadius: 8,
    padding: 8,
    marginHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  infoText: {
    flex: 1,
    fontSize: 12,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
  },
  linkText: {
    textDecorationLine: "underline",
    color: "#0062FF",
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 34,
    gap: 16,
    borderTopWidth: 1,
    borderTopColor: "#D1D1D6",
    zIndex: 1000,
  },
  lastUpdated: {
    textAlign: "center",
    fontSize: 12,
    fontFamily: "Nunito_300Light",
    color: "#1C0335",
  },
  button: {
    borderRadius: 8,
    height: 56,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
  },
  buttonPrimary: {
    backgroundColor: "#3B0076",
  },
  buttonSecondary: {
    borderWidth: 1,
    borderColor: "#3B0076",
  },
  buttonPrimaryText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
  },
  buttonSecondaryText: {
    color: "#3B0076",
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
  },
  // Bottom sheet styles
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  sheetContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    maxHeight: "92%",
    backgroundColor: "#F2F2F7",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingBottom: 40,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: -4 },
    shadowRadius: 12,
    elevation: 8,
    overflow: "hidden",
  },
  sheetHandle: {
    alignSelf: "center",
    width: 60,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#C8C7CC",
    marginTop: 8,
    marginBottom: 16,
  },
  sheetContent: { paddingHorizontal: 16, paddingBottom: 60, gap: 20 },
  sheetTitle: {
    fontSize: 24,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
    marginTop: 8,
  },
  fieldGroup: { gap: 8 },
  fieldLabel: { fontSize: 16, fontFamily: "Nunito_700Bold", color: "#1C0335" },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#AEAEB2",
    backgroundColor: "transparent",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  input: {
    flex: 1,
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
    padding: 0,
  },
  orDivider: { flexDirection: "row", alignItems: "center", gap: 12 },
  orLine: { flex: 1, height: 1, backgroundColor: "#D1D1D6" },
  orText: { fontSize: 14, fontFamily: "Nunito_700Bold", color: "#1C0335" },
  qtyRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#D1D1D6",
    backgroundColor: "#F1EFF5",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  qtyBtn: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  qtyBtnText: {
    fontSize: 28,
    color: "#1C0335",
    fontFamily: "Nunito_700Bold",
    lineHeight: 32,
  },
  qtyValue: { fontSize: 32, fontFamily: "Nunito_700Bold", color: "#1C0335" },
  textareaWrapper: { alignItems: "flex-start", paddingTop: 12 },
  textarea: { minHeight: 110, textAlignVertical: "top" },
  charCount: {
    position: "absolute",
    bottom: 8,
    right: 12,
    fontSize: 12,
    color: "#7A6F88",
    fontFamily: "Nunito_700Bold",
  },
  saveBtn: {
    height: 56,
    borderRadius: 8,
    backgroundColor: "#3B0076",
    alignItems: "center",
    justifyContent: "center",
  },
  saveBtnDisabled: { backgroundColor: "#D1D1D6" },
  saveBtnText: { fontSize: 18, fontFamily: "Nunito_700Bold", color: "#FFFFFF" },
  saveBtnTextDisabled: { color: "#8E8E93" },
  cancelBtn: {
    height: 56,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#3B0076",
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  cancelBtnText: {
    fontSize: 18,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
  },
  scrapeStatus: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#7A6F88",
  },
  errorText: { fontSize: 12, color: "#B00020", fontFamily: "Nunito_700Bold" },
  previewImage: {
    width: 120,
    height: 120,
    borderRadius: 12,
    marginTop: 8,
    backgroundColor: "#E1DEE6",
  },
  addMoreButton: {
    marginTop: 8,
    alignSelf: "center",
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#3B0076",
    backgroundColor: "#FFFFFF",
  },
  addMoreButtonText: {
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
  },
  addYourFirstGift: { paddingTop: 24, paddingHorizontal: 16, rowGap: 20 },
  // Legacy overlay (unused now) kept for reference
  browserOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#FFFFFF",
    elevation: 20,
  },
  browserHeader: {
    height: 56,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5EA",
    backgroundColor: "#F8F8FA",
  },
  browserHeaderBtn: { padding: 4 },
  browserTitle: {
    flex: 1,
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  webview: { flex: 1 },
  browserAddBtn: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 32,
    backgroundColor: "#3B0076",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 16,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 6,
  },
  browserAddBtnText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
  },
  browserModalContainer: { flex: 1, backgroundColor: "#FFFFFF" },
  browserActionBarWrapper: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  browserActionBar: {
    backgroundColor: "#3B0076",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 16,
    borderRadius: 8,
  },
  browserActionBarText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
  },
  // Sort & Filter sheet
  sortSheetContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    maxHeight: "80%",
  },
  sortSheetHandle: {
    width: 64,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#C7C7CC",
    alignSelf: "center",
    marginTop: 12,
  },
  sortSheetContent: {
    paddingBottom: 32,
    paddingHorizontal: 32,
    paddingTop: 8,
    gap: 24,
  },
  sortSheetTitle: {
    fontSize: 24,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
    textAlign: "center",
    marginTop: 24,
  },
  sortDivider: { height: 1, backgroundColor: "#E5E5EA" },
  sortSection: { gap: 12 },
  sortSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
  },
  sortSectionTitle: {
    fontSize: 20,
    fontFamily: "Nunito_900Black",
    color: "#1C0335",
  },
  radioRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 22,
    paddingVertical: 8,
  },
  radioOuter: {
    width: 24,
    height: 24,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#D5D2DA",
    alignItems: "center",
    justifyContent: "center",
  },
  radioOuterActive: { borderColor: "#360068", backgroundColor: "#360068" },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 9,
    backgroundColor: "#ffff",
  },
  radioLabel: {
    fontSize: 18,
    fontFamily: "Nunito_600SemiBold",
    color: "#1C0335",
  },
  checkboxBox: {
    width: 24,
    height: 24,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#D5D2DA",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxBoxActive: { borderColor: "#360068", backgroundColor: "#360068" },
  applyBarWrapper: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 24,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#E5E5EA",
  },
  applyBtnFull: {
    backgroundColor: "#360068",
    height: 56,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  applyBtnText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
  },
  // Spacer at bottom of scroll so content not hidden behind apply bar
  sortScrollSpacer: { height: 120 },
  selectedFilterContainer: {
    paddingVertical: 16,
    paddingLeft: 15,
    flexDirection: "row",
  },
  filterItem: { flexDirection: "row", gap: 8, flex: 1 },
  filterContent: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
  },
  filterTitle: { color: "#000000", fontFamily: "Nunito_700Bold", fontSize: 14 },
  filterValue: {
    textTransform: "capitalize",
    color: "#1C1C1CB2",
    fontFamily: "Nunito_700Bold",
    fontSize: 14,
    marginLeft: 5,
  },
  listCoverProfile: {
    position: "absolute",
    width: 33.3,
    height: 33.3,
    backgroundColor: "#3B0076",
    borderRadius: "50%",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    top: 21,
    left: 21,
  },
  listCoverProfileImageUrl: {
    width: "100%",
    height: "100%",
  },
  listCoverProfileInitials: {
    color: "#FFFF",
    fontSize: 12,
    fontFamily: "Nunito_700Bold",
    letterSpacing: 0,
  },
  filterContainer: {
    flexDirection: "row",
    flex: 1,
  },
  filterItemIcon: {
    width: 16,
    height: 16,
    tintColor: "#8D8D8D",
    marginTop: 5,
  },
  filterItemTitle: {
    fontSize: 12,
    fontFamily: "Nunito_700Bold",
    color: "#000000",
  },
  filterItemValue: {
    fontSize: 12,
    fontFamily: "Nunito_700Bold",
    color: "#1C1C1CB2",
  },
});

export const desktopStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F7F4FF",
  },
  safeArea: {
    flex: 1,
    backgroundColor: "#F7F4FF",
  },
  scrollContent: {
    paddingHorizontal: 48,
    paddingBottom: 96,
    paddingTop: 40,
  },
  maxWidth: {
    width: "100%",
    maxWidth: 1180,
    alignSelf: "center",
  },
  topBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 16,
    marginBottom: 28,
    zIndex: 100,
    overflow: "visible",
  },
  breadcrumbText: {
    fontSize: 14,
    fontFamily: "Nunito_600SemiBold",
    color: "#6D5C90",
  },
  breadcrumbCurrent: {
    color: "#3B0076",
    fontFamily: "Nunito_800ExtraBold",
  },
  topActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    overflow: "visible",
  },
  manageButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#DCCEF8",
    backgroundColor: "#FFFFFF",
  },
  manageButtonText: {
    color: "#3B0076",
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: "#03FFEE",
    shadowColor: "#03FFEE",
    shadowOpacity: 0.32,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 18,
    elevation: 6,
  },
  addButtonText: {
    color: "#1C0335",
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
  },
  heroCardWrapper: {
    position: "relative",
    marginBottom: 36,
  },
  heroCard: {
    position: "relative",
    borderRadius: 24,
    overflow: "visible",
    backgroundColor: "#4F0EA2",
  },
  heroImage: {
    width: "100%",
    height: 260,
    borderRadius: 24,
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "flex-end",
    justifyContent: "flex-start",
    paddingTop: 20,
    paddingRight: 20,
  },
  changeCoverButton: {
    backgroundColor: "#03FFEE",
    paddingHorizontal: 9,
    height: 28,
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  changeCoverText: {
    color: "#1C0335",
    fontFamily: "Nunito_700Bold",
    fontSize: 14,
  },
  ribbonContainer: {
    position: "absolute",
    bottom: -40,
    left: 0,
    right: 0,
    alignItems: "center",
    zIndex: 10,
  },
  statsRow: {
    flexDirection: "row",
    gap: 16,
    marginTop: 64,
    marginBottom: 24,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 48,
  },
  statCard: {
    flex: 0,
    minWidth: 213,
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 120,
  },
  statCardLabel: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#FFFFFF",
    marginBottom: 8,
    textAlign: "center",
  },
  statCardValue: {
    fontSize: 40,
    fontFamily: "Nunito_700Bold",
    color: "#FFFFFF",
    textAlign: "center",
  },
  controlsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 20,
    alignItems: "center",
    marginTop: 24,
    marginBottom: 18,
  },
  visibilityTrigger: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FFFFFF",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E5E0F5",
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  visibilityText: {
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  filterCluster: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    flex: 1,
    flexWrap: "wrap",
    minWidth: 260,
  },
  filterGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  filterLabel: {
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
    flexShrink: 0,
  },
  filterButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#3B0076",
    backgroundColor: "#FFFFFF",
    minWidth: 104,
    flexShrink: 0,
  },
  filterButtonText: {
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
  },
  shareLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E5EA",
  },
  shareLinkText: {
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
  },
  sectionDivider: {
    height: 1,
    backgroundColor: "#E5E5EA",
    marginBottom: 18,
  },
  addressNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 16,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E5EA",
    marginBottom: 18,
  },
  addressText: {
    flex: 1,
    fontSize: 14,
    fontFamily: "Nunito_600SemiBold",
    color: "#1C0335",
  },
  listSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  listSummaryLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  listSummaryLabel: {
    fontSize: 18,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  listSummaryBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#3B0076",
  },
  listSummaryBadgeText: {
    fontSize: 18,
    fontFamily: "Nunito_700Bold",
    color: "#FFFFFF",
  },
  summaryShare: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  summaryShareText: {
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
  },
  itemsColumn: {
    gap: 18,
    marginBottom: 28,
  },
  itemRow: {
    flexDirection: "row",
    gap: 18,
    padding: 20,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E6E1F3",
    shadowColor: "#2D0F54",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 20,
    elevation: 4,
  },
  itemIndexBubble: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F1ECFF",
    alignItems: "center",
    justifyContent: "center",
  },
  itemIndexText: {
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
  },
  itemImageWrapper: {
    width: 110,
    height: 110,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E7E0F4",
    alignItems: "center",
    justifyContent: "center",
  },
  itemImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  itemImagePlaceholder: {
    width: "100%",
    height: "100%",
    backgroundColor: "#F1ECFF",
  },
  itemDetails: {
    flex: 1,
    gap: 12,
  },
  itemHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 20,
  },
  itemTitleBlock: {
    flex: 1,
    gap: 6,
  },
  itemName: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  itemDescription: {
    fontSize: 14,
    fontFamily: "Nunito_400Regular",
    color: "#595970",
  },
  itemActionsColumn: {
    alignItems: "flex-end",
    gap: 10,
  },
  buyButton: {
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: "#03FFEE",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 140,
  },
  buyButtonDisabled: {
    backgroundColor: "#D7D7DD",
  },
  buyButtonText: {
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  buyButtonTextDisabled: {
    color: "#6B7280",
  },
  deleteButton: {
    width: 38,
    height: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#F8C7CF",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFE9EE",
  },
  itemMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 18,
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  priceCurrency: {
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
    color: "#F2994A",
  },
  priceText: {
    fontSize: 20,
    fontFamily: "Nunito_700Bold",
    color: "#F2994A",
  },
  quantityText: {
    fontSize: 14,
    fontFamily: "Nunito_600SemiBold",
    color: "#1C0335",
  },
  statusBadge: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 999,
  },
  statusBadgeSuccess: {
    backgroundColor: "#D4F5E5",
  },
  statusBadgeWarning: {
    backgroundColor: "#FFF2D6",
  },
  statusBadgeNeutral: {
    backgroundColor: "#E8E8ED",
  },
  statusBadgeText: {
    fontSize: 12,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  statusBadgeSuccessText: {
    color: "#1F6F4A",
  },
  statusBadgeWarningText: {
    color: "#B07219",
  },
  statusBadgeNeutralText: {
    color: "#5F5F6B",
  },
  progressTrack: {
    height: 6,
    backgroundColor: "#E3E1ED",
    borderRadius: 4,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#3B0076",
    borderRadius: 4,
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingVertical: 46,
    paddingHorizontal: 32,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E7E0F4",
  },
  emptyTitle: {
    fontSize: 20,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  emptySubtitle: {
    fontSize: 14,
    fontFamily: "Nunito_400Regular",
    color: "#6F5A92",
    textAlign: "center",
  },
  addButtonSecondary: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#3B0076",
    backgroundColor: "#FFFFFF",
  },
  addButtonSecondaryText: {
    color: "#3B0076",
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
  },
  lastUpdated: {
    textAlign: "center",
    fontSize: 13,
    fontFamily: "Nunito_600SemiBold",
    color: "#6F5A92",
  },
  menuBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  menuCard: {
    width: 280,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    paddingVertical: 12,
    shadowColor: "#2D0F54",
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 12 },
    shadowRadius: 22,
    elevation: 6,
  },
  menuRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  menuLabel: {
    fontSize: 16,
    fontFamily: "Nunito_600SemiBold",
    color: "#1C0335",
  },
  // Web Modal Styles
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  modalContent: {
    width: "100%",
    maxWidth: 800,
    maxHeight: Platform.OS === "web" ? "90vh" : undefined,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    shadowColor: Platform.OS !== "web" ? "#000" : undefined,
    shadowOpacity: Platform.OS !== "web" ? 0.15 : undefined,
    shadowOffset: Platform.OS !== "web" ? { width: 0, height: 20 } : undefined,
    shadowRadius: Platform.OS !== "web" ? 60 : undefined,
    elevation: Platform.OS !== "web" ? 8 : undefined,
    overflow: "hidden",
    flexDirection: "column",
  } as any,
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 32,
    paddingTop: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5EA",
  },
  modalTitle: {
    fontSize: 24,
    fontFamily: "Nunito_700Bold",
    color: "#330065",
  },
  modalCloseButton: {
    padding: 4,
  },
  modalScrollContent: {
    paddingHorizontal: 32,
    paddingVertical: 24,
    gap: 24,
  },
  modalFieldGroup: {
    gap: 12,
  },
  modalFieldLabel: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  modalInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  modalInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#D1D1D6",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#1C0335",
    backgroundColor: "#FFFFFF",
  },
  modalSearchButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D1D1D6",
    backgroundColor: "#FFFFFF",
  },
  modalSearchButtonText: {
    fontSize: 16,
    fontFamily: "Nunito_600SemiBold",
    color: "#1C0335",
  },
  googleLogo: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#4285F4",
    alignItems: "center",
    justifyContent: "center",
  },
  googleG: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#FFFFFF",
  },
  modalErrorText: {
    fontSize: 12,
    fontFamily: "Nunito_700Bold",
    color: "#B00020",
    marginTop: 4,
  },
  modalScrapingText: {
    fontSize: 14,
    fontFamily: "Nunito_400Regular",
    color: "#7A6F88",
    marginTop: 4,
  },
  modalProductRow: {
    flexDirection: "row",
    gap: 24,
    alignItems: "flex-start",
  },
  modalImageContainer: {
    width: 280,
    minHeight: 280,
  },
  modalImageWrapper: {
    width: "100%",
    height: 280,
    borderRadius: 16,
    backgroundColor: "#F5F5F5",
    borderWidth: 1,
    borderColor: "#E5E5EA",
    overflow: "hidden",
    position: "relative",
  },
  modalProductImage: {
    width: "100%",
    height: "100%",
  },
  modalImageEditButton: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: Platform.OS !== "web" ? "#000" : undefined,
    shadowOpacity: Platform.OS !== "web" ? 0.1 : undefined,
    shadowOffset: Platform.OS !== "web" ? { width: 0, height: 2 } : undefined,
    shadowRadius: Platform.OS !== "web" ? 8 : undefined,
    elevation: Platform.OS !== "web" ? 2 : undefined,
  } as any,
  modalImagePlaceholder: {
    width: "100%",
    height: 280,
    borderRadius: 16,
    backgroundColor: "#F5F5F5",
    borderWidth: 1,
    borderColor: "#E5E5EA",
    alignItems: "center",
    justifyContent: "center",
  },
  modalPriceQtyColumn: {
    flex: 1,
    gap: 24,
  },
  modalPriceInput: {
    borderWidth: 1,
    borderColor: "#D1D1D6",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 18,
    fontFamily: "Nunito_700Bold",
    color: "#F2994A",
    backgroundColor: "#FFFFFF",
  },
  modalQtyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    borderWidth: 1,
    borderColor: "#D1D1D6",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "#F5F5F5",
  },
  modalQtyButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#D1D1D6",
  },
  modalQtyButtonText: {
    fontSize: 24,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
    lineHeight: 28,
  },
  modalQtyValue: {
    fontSize: 24,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
    minWidth: 40,
    textAlign: "center",
  },
  modalTextareaWrapper: {
    position: "relative",
    borderWidth: 1,
    borderColor: "#D1D1D6",
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    minHeight: 120,
  },
  modalTextarea: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 32,
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#1C0335",
    textAlignVertical: "top",
    minHeight: 120,
  },
  modalCharCount: {
    position: "absolute",
    bottom: 12,
    right: 16,
    fontSize: 12,
    fontFamily: "Nunito_400Regular",
    color: "#8E8EA9",
  },
  modalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 16,
    paddingHorizontal: 32,
    paddingVertical: 24,
    borderTopWidth: 1,
    borderTopColor: "#E5E5EA",
  },
  modalCancelButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#3B0076",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  modalCancelButtonText: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
  },
  modalSaveButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: "#3B0076",
    alignItems: "center",
    justifyContent: "center",
  },
  modalSaveButtonDisabled: {
    backgroundColor: "#D1D1D6",
  },
  modalSaveButtonText: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#FFFFFF",
  },
  modalSaveButtonTextDisabled: {
    color: "#8E8E93",
  },
});
