import { StyleSheet } from "react-native";
export const giftDetailsStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F7F4FF",
  },
  safeArea: {
    flex: 1,
    backgroundColor: "#F7F4FF",
  },
  scrollContent: {
    paddingHorizontal: 48,
    paddingVertical: 48,
  },
  maxWidth: {
    width: "100%",
    maxWidth: 1200,
    alignSelf: "center",
    gap: 32,
  },
  breadcrumbRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    gap: 16,
  },
  backPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E0F5",
    shadowColor: "#3B0076",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  backPillText: {
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
  },
  breadcrumbText: {
    flex: 1,
    textAlign: "right",
    fontSize: 14,
    fontFamily: "Nunito_600SemiBold",
    color: "#6B5E7E",
  },
  heroRow: {
    flexDirection: "row",
    gap: 32,
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  productCard: {
    flex: 1,
    minWidth: 360,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 32,
    borderWidth: 1,
    borderColor: "#E6E1F3",
    shadowColor: "#190A33",
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 14 },
  },
  productImageWrap: {
    width: "100%",
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#F2EEFB",
    marginBottom: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  productImage: {
    width: "100%",
    height: 280,
    resizeMode: "cover",
  },
  productContent: {
    gap: 12,
  },
  productTitle: {
    fontSize: 28,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  productPrice: {
    fontSize: 22,
    fontFamily: "Nunito_700Bold",
    color: "#F2994A",
  },
  productQuantity: {
    fontSize: 16,
    fontFamily: "Nunito_600SemiBold",
    color: "#5C4F76",
  },
  productQuantityValue: {
    fontFamily: "Nunito_800ExtraBold",
  },
  productDescription: {
    fontSize: 15,
    color: "#6B5E7E",
    fontFamily: "Nunito_400Regular",
    lineHeight: 22,
  },
  productMeta: {
    fontSize: 13,
    fontFamily: "Nunito_500Medium",
    color: "#6B5E7E",
  },
  productActions: {
    flexDirection: "row",
    gap: 16,
    marginTop: 24,
    flexWrap: "wrap",
  },
  primaryButton: {
    flexGrow: 1,
    minWidth: 160,
    backgroundColor: "#3B0076",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonDisabled: {
    backgroundColor: "#C9C5D6",
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
  },
  primaryButtonTextDisabled: {
    color: "#6B5E7E",
  },
  secondaryButton: {
    flexGrow: 1,
    minWidth: 160,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#3B0076",
    backgroundColor: "#FFFFFF",
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonText: {
    color: "#3B0076",
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
  },
  detailsCard: {
    flexBasis: 400,
    flexGrow: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    paddingVertical: 32,
    paddingHorizontal: 28,
    borderWidth: 1,
    borderColor: "#E6E1F3",
    shadowColor: "#190A33",
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 14 },
  },
  detailsTitle: {
    fontSize: 26,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  detailsSubtitle: {
    fontSize: 14,
    color: "#6B5E7E",
    fontFamily: "Nunito_500Medium",
    marginTop: 6,
  },
  detailsForm: {
    marginTop: 28,
    gap: 24,
  },
  formBlock: {
    gap: 12,
  },
  toggleGroup: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0E9FF",
    borderRadius: 999,
    padding: 6,
    gap: 6,
    alignSelf: "flex-start",
  },
  toggleButton: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
  },
  toggleButtonActive: {
    backgroundColor: "#FFFFFF",
    shadowColor: "#26084D",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  toggleButtonText: {
    fontSize: 14,
    fontFamily: "Nunito_600SemiBold",
    color: "#5C4F76",
  },
  toggleButtonTextActive: {
    color: "#1C0335",
  },
  stepperRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 18,
  },
  fieldTitle: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  stepper: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  stepperButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#3B0076",
    shadowColor: "#26084D",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  stepperButtonDisabled: {
    opacity: 0.4,
  },
  stepperButtonText: {
    fontSize: 22,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
    lineHeight: 22,
  },
  stepperValue: {
    fontSize: 24,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
    minWidth: 38,
    textAlign: "center",
  },
  radioGroup: {
    gap: 12,
  },
  radioOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E0EC",
    backgroundColor: "#FFFFFF",
  },
  radioOptionActive: {
    borderColor: "#3B0076",
    backgroundColor: "#F3EEFF",
  },
  radioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#CFC7DD",
    alignItems: "center",
    justifyContent: "center",
  },
  radioCircleActive: {
    borderColor: "#3B0076",
  },
  radioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#3B0076",
  },
  radioLabel: {
    fontSize: 14,
    fontFamily: "Nunito_600SemiBold",
    color: "#1C0335",
  },
  noteWrapper: {
    borderWidth: 1,
    borderColor: "#E6E1F3",
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    paddingVertical: 14,
    minHeight: 120,
  },
  noteInput: {
    color: "#1C0335",
    fontFamily: "Nunito_500Medium",
    fontSize: 14,
    lineHeight: 20,
    textAlignVertical: "top",
    minHeight: 70,
  },
  charCounter: {
    fontSize: 12,
    fontFamily: "Nunito_600SemiBold",
    color: "#8E86A6",
    textAlign: "right",
    marginTop: 8,
  },
  storeRow: {
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
  },
  storeCard: {
    flex: 1,
    minWidth: 160,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: "#E5E0EC",
    backgroundColor: "#FFFFFF",
    paddingVertical: 18,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  storeCardNeutral: {
    borderColor: "#E5E0EC",
    backgroundColor: "#F7F4FF",
  },
  storeCardActive: {
    borderColor: "#3B0076",
    shadowColor: "#3B0076",
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  storeCardDisabled: {
    opacity: 0.4,
  },
  storeCardLabel: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  storeCardLabelActive: {
    color: "#1C0335",
  },
  inputField: {
    gap: 8,
  },
  fieldLabel: {
    fontSize: 13,
    fontFamily: "Nunito_600SemiBold",
    color: "#6B5E7E",
  },
  textInputWrapper: {
    borderWidth: 1,
    borderColor: "#E5E0EC",
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 14,
    height: 52,
    justifyContent: "center",
  },
  textInput: {
    fontSize: 15,
    fontFamily: "Nunito_600SemiBold",
    color: "#1C0335",
  },
  placeholderBox: {
    marginTop: 24,
    padding: 18,
    borderRadius: 16,
    backgroundColor: "#F7F3FB",
    borderWidth: 1,
    borderColor: "#E5E0EC",
  },
  placeholderText: {
    fontSize: 14,
    color: "#6B5E7E",
    fontFamily: "Nunito_500Medium",
    lineHeight: 20,
  },
  moreSection: {
    marginTop: 48,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    paddingVertical: 28,
    paddingHorizontal: 32,
    borderWidth: 1,
    borderColor: "#E6E1F3",
    shadowColor: "#190A33",
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
  },
  moreHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
    gap: 16,
  },
  moreTitle: {
    fontSize: 20,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  seeAllButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#3B0076",
    backgroundColor: "#FFFFFF",
  },
  seeAllText: {
    color: "#3B0076",
    fontFamily: "Nunito_700Bold",
    fontSize: 14,
  },
  moreGrid: {
    gap: 18,
  },
  moreCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
    padding: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#ECE6F7",
    backgroundColor: "#FFFFFF",
  },
  moreImageWrap: {
    width: 120,
    height: 120,
    borderRadius: 18,
    backgroundColor: "#F2EEFB",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  moreImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  moreBody: {
    flex: 1,
    gap: 8,
  },
  moreName: {
    fontSize: 18,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  morePrice: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#F2994A",
  },
  moreQuantity: {
    fontSize: 14,
    fontFamily: "Nunito_600SemiBold",
    color: "#5C4F76",
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "#EBE3FF",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#4B0082",
  },
  moreMeta: {
    fontSize: 13,
    color: "#6B5E7E",
    fontFamily: "Nunito_500Medium",
  },
  moreBuyButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#3B0076",
    backgroundColor: "#FFFFFF",
  },
  moreBuyText: {
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
  },
  buttonRow: {
    flexDirection: "row",
    gap: 16,
    marginTop: 32,
    flexWrap: "wrap",
  },
  backButton: {
    flexGrow: 1,
    minWidth: 140,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#3B0076",
    backgroundColor: "#FFFFFF",
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  backButtonText: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#3B0076",
  },
  submitButton: {
    flexGrow: 1,
    minWidth: 160,
    borderRadius: 14,
    backgroundColor: "#3B0076",
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  submitButtonDisabled: {
    backgroundColor: "#C9C5D6",
  },
  submitButtonText: {
    fontSize: 16,
    fontFamily: "Nunito_700Bold",
    color: "#FFFFFF",
  },
  helperFootnote: {
    marginTop: 18,
    fontSize: 12,
    fontFamily: "Nunito_500Medium",
    color: "#6B5E7E",
  },
});