import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    fontFamily: "Nunito_400Regular",
  },
  header: {
    fontFamily: "Nunito_400Regular",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: "#330065",
  },
  searchContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    borderColor: "#FFFFFF",
    borderWidth: 1,
    borderRadius: 25,
    paddingHorizontal: 15,
    paddingVertical: 12,
    marginRight: 15,
  },
  searchInput: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 14,
    fontFamily: "Nunito_400Regular",
    marginLeft: 10,
  },
  profileButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: "hidden",
  },
  profileImage: {
    position: "relative",
    width: 40,
    height: 48,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
  },
  profileText: {
    fontSize: 20,
    fontFamily: "Nunito_400Regular",
  },
  welcomeSection: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: "#FFF",
  },
  welcomeTitle: {
    fontSize: 40,
    fontWeight: "bold",
    fontFamily: "Nunito_700Bold",
    color: "#00",
  },
  welcomeSubtitle: {
    fontSize: 24,
    fontFamily: "Nunito_400Regular",
    color: "#000",
  },
  addListContainer: {
    position: "relative",
    paddingHorizontal: 10,
    paddingTop: 0,
    zIndex: 10,
    paddingBottom: 80,
    backgroundColor: "#FFF",
  },
  cardStack: {
    position: "absolute",
    height: 180,
    zIndex: 10,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  sideCard: {
    transitionDuration: "0",
    position: "absolute",
    backgroundColor: "rgba(255, 255, 255, 1)",
    borderRadius: 20,
    width: 180,
    height: 220,
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  leftCard: {
    transitionDuration: "0",
    position: "absolute",
    backgroundColor: "#E9FFE2",
    borderRadius: 20,
    width: 167,
    height: 250,
    padding: 15,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "20deg" }],
    left: 50,
    top: -74,
  },
  rightCard: {
    transitionDuration: "0",
    position: "absolute",
    backgroundColor: "#C2D9FF",
    borderRadius: 20,
    width: 167,
    height: 250,
    padding: 15,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "-20deg" }],
    right: 50,
    top: -74,
  },
  mainCard: {
    transitionDuration: "0",
    position: "absolute",
    backgroundColor: "#F3ECFE",
    borderRadius: 20,
    width: 200,
    height: 263,
    top: -74,
    left: -96,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 8,
    padding: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  addIconContainer: {
    width: 85,
    height: 96,
    right: -6,
    alignItems: "center",
    justifyContent: "center",
  },
  addListTitle: {
    fontSize: 24,
    fontWeight: "bold",
    fontFamily: "Nunito_700Bold",
    color: "#1F2937",
    marginBottom: 4,
    textAlign: "center",
  },
  addListSubtitle: {
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#6B7280",
    textAlign: "center",
    lineHeight: 14,
    paddingHorizontal: 4,
  },
  carouselContainer: {
    paddingVertical: 20,
    backgroundColor: "#FFF",
    height: 300,
  },
  carouselCard: {
    borderRadius: 20,
    height: 240,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 8,
    padding: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  section: {
    position: "relative",
    paddingHorizontal: 20,
    backgroundColor: "#330065",
    paddingVertical: 20,
    zIndex: 1,
  },
  isection: {
    position: "relative",
    paddingHorizontal: 20,
    backgroundColor: "white",
    paddingVertical: 20,
  },
  eventSection: {
    position: "relative",
    paddingHorizontal: 20,
    backgroundColor: "#FFF",
    paddingVertical: 20,
    zIndex: 1,
  },
  topSection: {
    position: "relative",
    paddingHorizontal: 20,
    backgroundColor: "#EEEEEE",
    paddingVertical: 20,
    zIndex: 1,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: "bold",
    fontFamily: "Nunito_700Bold",
    color: "black",
  },
  eventSectionTitle: {
    fontSize: 24,
    fontFamily: "Nunito_700Bold",
    color: "black",
    marginBottom: 8,
  },
  sectionTitleCategory: {
    fontSize: 24,
    marginBottom: 20,
    fontWeight: "bold",
    fontFamily: "Nunito_700Bold",
    color: "white",
  },
  categoriesScroll: {
    marginHorizontal: -20,
    paddingHorizontal: 20,
  },
  categoriesContainer: {
    paddingRight: 0,
  },
  categoriesRow: {
    flexDirection: "row",
    marginBottom: 8,
  },
  categoryCard: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderTopEndRadius: 8,
    borderTopStartRadius: 8,
    width: 130,
    fontFamily: "Nunito_400Regular",
    fontSize: 16,
    height: 100,
    marginRight: 8,
    overflow: "hidden",
  },
  categoryContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
  },
  categoryIconContainer: {
    marginBottom: 8,
  },
  categoryIcon: {
    width: 24,
    height: 24,
    tintColor: "#FFFFFF",
  },
  categoryName: {
    fontSize: 14,
    fontFamily: "Nunito_500Medium",
    color: "#FFFFFF",
    textAlign: "center",
    fontWeight: "500",
  },
  categoryBorder: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 4,
  },
  eventsScroll: {
    marginHorizontal: -20,
    paddingHorizontal: 20,
  },
  eventCard: {
    backgroundColor: "#FFFFFF",
    marginRight: 22,
    width: 190,
    overflow: "hidden",
    position: "relative",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  eventLeftBorder: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 8,
  },
  eventContent: {
    marginLeft: 8,
    flexDirection: "column",
    padding: 15,
    alignItems: "flex-start",
    gap: 16,
  },
  eventDateContainer: {
    marginRight: 15,
    alignItems: "center",
    fontWeight: "900",
    fontFamily: "Nunito_900Black",
  },
  eventDateNumber: {
    fontSize: 40,
    fontWeight: "900",
    fontFamily: "Nunito_900Black",
    color: "#1C1C1C",
    // Prevent clipping on iOS by ensuring lineHeight >= fontSize
    lineHeight: 44,
    paddingTop: 2,
    paddingBottom: 2,
  },
  eventDateMonth: {
    fontSize: 20,
    fontWeight: "900",
    fontFamily: "Nunito_900Black",
    color: "#1C1C1C",
    textTransform: "uppercase",
  },
  eventInfo: {
    flex: 1,
  },
  eventTitle: {
    fontSize: 20,
    fontWeight: "600",
    fontFamily: "Nunito_600SemiBold",
    color: "#1C1C1C",
  },
  eventSubtitle: {
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#1C1C1C",
  },
  picksScroll: {
    marginHorizontal: -20,
    paddingHorizontal: 20,
  },
  pickCard: {
    backgroundColor: "#F9FAFB",
    borderRadius: 18,
    padding: 8,
    marginRight: 16,
    width: 200,
  },
  pickImageContainer: {
    width: 182,
    height: 146,
    borderRadius: 8,
    marginBottom: 10,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
  },
  pickEmoji: {
    fontSize: 32,
  },
  pickName: {
    fontSize: 20,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
    color: "#1C1C1C",
    marginBottom: 2,
    marginLeft: 12,
  },
  pickSubtitle: {
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#6B7280",
    marginBottom: 16,
    marginLeft: 12,
  },
  pickPrice: {
    fontSize: 16,
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontWeight: "900",
    fontFamily: "Nunito_900Black",
    color: "#1F2937",
    marginLeft: 12,
  },
  inspirationCard: {
    flexDirection: "row",
    gap: 8,
    backgroundColor: "#EEEEEE",
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
  },
  inspirationImageContainer: {
    width: 148,
    height: 148,
    borderRadius: 8,
    backgroundColor: "#EEEEEE",
    alignItems: "center",
    justifyContent: "center",
  },
  inspirationEmoji: {
    fontSize: 24,
  },
  inspirationContent: {
    flex: 1,
  },
  inspirationTitle: {
    fontSize: 20,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
    color: "#1F2937",
    marginBottom: 4,
  },
  inspirationSubtitle: {
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#1C1C1C",
    lineHeight: 20,
  },
  aiSection: {
    backgroundColor: "#330065",
    padding: 20,
    position: "relative",
    overflow: "hidden",
    zIndex: 1,
  },
  aiHeader: {
    alignItems: "flex-start",
    marginBottom: 10,
  },
  aiButton: {
    backgroundColor: "#03FFEE",
    color: "#330065",
    fontSize: 10,
    fontFamily: "Nunito_700Bold",
    fontWeight: "bold",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
  },
  aiTitle: {
    fontSize: 40,
    fontWeight: "bold",
    fontFamily: "Nunito_700Bold",
    color: "#FFFFFF",
    marginBottom: 10,
  },
  aiDescription: {
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#FFFFFF",
    lineHeight: 20,
    marginBottom: 20,
    maxWidth: "80%",
  },
  aiChatButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  aiRobotContainer: {
    position: "absolute",
    right: 20,
    bottom: 20,
    alignItems: "center",
  },
  aiRobot: {
    width: 80,
    height: 80,
    backgroundColor: "#FFFFFF",
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  robotImage: {
    width: 374,
    height: 300,
  },
  aiLogo: {
    backgroundColor: "#4C1D95",
    borderRadius: 15,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginTop: 10,
  },
  aiLogoText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "bold",
    fontFamily: "Nunito_700Bold",
  },
});
