import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F6F3FF",
  },
  headerWrapper: {
    backgroundColor: "#2C0077",
  },
  navBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 28,
    paddingVertical: 18,
  },
  navBrandRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  navBrandLogo: {
    width: 164,
    height: 32,
  },
  navActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 24,
  },
  navAuthLink: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 16,
    color: "#FFFFFF",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 24,
    backgroundColor: "#2C0077",
  },
  searchContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 999,
    paddingHorizontal: 22,
    paddingVertical: 12,
  },
  mobileSearchContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.4)",
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  searchInput: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 14,
    fontFamily: "Nunito_400Regular",
    marginLeft: 12,
  },
  profileButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(51, 0, 101, 0.12)",
  },
  profileImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  profileAvatarImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  profileText: {
    fontSize: 20,
    fontFamily: "Nunito_600SemiBold",
    color: "#330065",
  },
  heroSection: {
    // backgroundColor: "#F6F0FF",
    paddingHorizontal: 20,
    paddingTop: 32,
    paddingBottom: 24,
  },
  heroContent: {
    maxWidth: 520,
  },
  heroEyebrow: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 14,
    color: "#7D72A5",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 12,
  },
  welcomeTitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 62,
    color: "#330065",
    marginTop: 8,
    textAlign:'center',
  },
  welcomeTitleMobile: {
    fontSize: 32,
    textAlign:'left',
  },


  welcomeSubtitle: {
    fontSize: 32,
    fontFamily: "Nunito_400Regular",
    color: "#514A6E",
    marginTop: 16,
    lineHeight: 26,
    textAlign:'center'
  },
  welcomeSubtitleMobile : {
    fontSize: 18,
    fontFamily: "Nunito_400Regular",
    color: "#514A6E",
    marginTop: 16,
    lineHeight: 26,
  },
  heroActions: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    marginTop: 28,
  },
  heroPrimaryButton: {
    backgroundColor: "#330065",
    borderRadius: 16,
    paddingHorizontal: 24,
    paddingVertical: 14,
    marginRight: 14,
    marginBottom: 12,
  },
  heroPrimaryButtonText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 15,
    color: "#FFFFFF",
  },
  heroSecondaryButton: {
    backgroundColor: "#E6DEFF",
    borderRadius: 16,
    paddingHorizontal: 22,
    paddingVertical: 14,
    marginBottom: 12,
  },
  heroSecondaryButtonText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 15,
    color: "#330065",
  },
  heroTagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 20,
  },
  heroTag: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: "rgba(51, 0, 101, 0.08)",
    marginRight: 12,
    marginBottom: 12,
  },
  heroTagText: {
    fontFamily: "Nunito_500Medium",
    fontSize: 14,
    color: "#352A66",
  },
  heroVisual: {
    flex: 1,
    justifyContent: "center",
    paddingTop: 28,
  },
  heroSwiperContainer: {
    width: "100%",
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  heroSwipeLabel: {
    position: "absolute",
    bottom: 0,
    alignSelf: "center",
    fontSize: 12,
    fontFamily: "Nunito_500Medium",
    color: "#6E6E73",
    letterSpacing: 0.3,
  },
  addListTitle: {
    fontSize: 20,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
    marginBottom: 6,
  },
  addListSubtitle: {
    fontSize: 13,
    fontFamily: "Nunito_400Regular",
    color: "#4B3D66",
    lineHeight: 18,
    maxWidth: 220,
  },
  heroCardTitle: {
    fontSize: 20,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
    marginBottom: 6,
  },
  heroCardSubtitle: {
    fontSize: 13,
    fontFamily: "Nunito_400Regular",
    color: "#4B3D66",
    lineHeight: 18,
    maxWidth: 200,
  },
  lifeMomentsSection: {
    backgroundColor: "#FFFFFF",
    paddingVertical: 40,
  },
  lifeMomentsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  lifeMomentsEyebrow: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 14,
    color: "#7D72A5",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  lifeMomentsTitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 60,
    color: "#330065",
    marginTop: 8,
    textAlign:'center',
    lineHeight: 23.33,
    marginBottom: 60,
  },
  lifeMomentsTitleMobile: {
    fontSize: 32,
    textAlign:'left',

  },
  sectionAction: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(51, 0, 101, 0.08)",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  sectionActionText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 14,
    color: "#524D70",
    marginRight: 8,
  },
  lifeMomentsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 54.5,
  },
  lifeMomentsScroll: {
    marginHorizontal: -20,
  },
  lifeMomentsSecondarySection: {
    backgroundColor: "#2D0353",
    paddingVertical: 44,
    paddingHorizontal: 20,
  },
  lifeMomentsSecondaryHeader: {
    marginBottom: 28,
  },
  lifeMomentsSecondaryTitle: {
    color: "#FFFFFF",
    fontFamily: "Nunito_700Bold",
    fontSize: 60,
    marginTop: 8,
    textAlign:'center',
    lineHeight: 23.33,
    marginBottom: 60,
  },
   lifeMomentsSecondaryTitleMobile: {
    fontSize: 32,
    textAlign:'left',
  },
  lifeMomentsSecondarySubtitle: {
    fontFamily: "Nunito_400Regular",
    fontSize: 16,
    color: "rgba(255, 255, 255, 0.75)",
    marginTop: 10,
    lineHeight: 24,
  },
  lifeMomentCard: {
    borderRadius: 20,
    padding: 24,
    borderWidth: 3.11,
    borderColor: "transparent",
    // marginBottom: 20,
    overflow: "hidden",

  },
  lifeMomentCardSecondary: {
    borderColor: "rgba(255, 255, 255, 0.24)",
  },
  lifeMomentBadge: {
    width: 48,
    height: 6,
    borderRadius: 999,
    marginBottom: 16,
  },
  lifeMomentTitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 28,
    color: "#1C0335",
  },
  lifeMomentTitleMobile: {
    fontSize: 20,
  },
  renderLifeMomentCardIcon: {
     width: 70,
     height: 70,
     objectFit:'contain',
     marginBottom: 33
  },
  renderLifeMomentCardArrowIcon: {
     width: 16.06,
     height: 15.54 ,
     objectFit:'contain',
     marginTop: 16.58
  },
  lifeMomentCaption: {
    fontFamily: "Nunito_400Regular",
    fontSize: 18,
    color: "#1C1C1C",
    marginTop: 8,
    lineHeight: 20,
  },
   lifeMomentCaptionMobile: {
    fontSize: 18,
  },
  categoryCardsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  categoriesRow: {
    flexDirection: "row",
    width:'100%',
    alignItems:'center',
    justifyContent:'space-between',
  },
  categoriesRowMobile: {
    justifyContent:'flex-start',
    columnGap: 5
  },
  categoryCard: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderTopEndRadius: 20.81,
    borderTopStartRadius: 20.81,
    fontFamily: "Nunito_400Regular",
    overflow: "hidden",
    borderBottomWidth: 8.6
  },

  categoryCardDesktop: {
    width: '23%',
    height: 277,
  },
  categoryCardMobile : {
    width: 140,
    height: 120,
    borderTopEndRadius: 8,
    borderTopStartRadius: 8,
    borderBottomWidth: 4,
  },

  categoryContent: {
    justifyContent:'center',
    alignItems:'center',
    height:'100%',
    gap: 36
  },
  categoryContentMobile: {
    justifyContent:'center',
    alignItems:'center',
    height:'100%',
    gap: 16
  },

 categoryIcon: {
    width: 72,
    height: 72,
  },
  categoryIconMobile: {
    width: 24,
    height: 24,
  },

  categoryNameMobile: {
    fontSize: 12,
    fontFamily: "Nunito_500Medium",
    color: "#FFFFFF",
    textAlign: "center",
    fontWeight: "500",
  },
  categoryName: {
    fontSize: 31,
    fontFamily: "Nunito_700Bold",
    color: "#FFFFFF",
    textAlign: "center",
    fontWeight: "500",
  },

  arrowWhiteIconDesktop : {
    width: 18,
    height: 17,
    objectFit: "contain"
  },
   arrowWhiteIconMobile : {
    width: 15,
    height: 14,
    objectFit: "contain"
  },
  section: {
    paddingHorizontal: 20,
    paddingVertical: 32,
    backgroundColor: "#FFFFFF",
  },
  isection: {
    paddingHorizontal: 20,
    paddingVertical: 36,
    backgroundColor: "#FFFFFF",
  },
  eventSection: {
    paddingHorizontal: 20,
    paddingVertical: 36,
    backgroundColor: "#FFFFFF",
  },
  topSection: {
    paddingHorizontal: 20,
    paddingVertical: 36,
    backgroundColor: "#F8F5FF",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 26,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  eventSectionTitle: {
    fontSize: 26,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
  },
  eventsScroll: {
    marginHorizontal: -20,
    paddingHorizontal: 20,
  },
  eventCard: {
    backgroundColor: "#FFFFFF",
    marginRight: 22,
    width: 220,
    overflow: "hidden",
    position: "relative",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E8E3F7",
  },
  eventLeftBorder: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 8,
  },
  eventContent: {
    flexDirection: "row",
    padding: 20,
    alignItems: "flex-start",
  },
  eventDateContainer: {
    marginRight: 16,
    alignItems: "center",
  },
  eventDateNumber: {
    fontSize: 42,
    fontFamily: "Nunito_900Black",
    color: "#1C0335",
    lineHeight: 44,
  },
  eventDateMonth: {
    fontSize: 14,
    fontFamily: "Nunito_700Bold",
    color: "#5E5681",
    textTransform: "uppercase",
    marginTop: 4,
  },
  eventInfo: {
    flex: 1,
  },
  eventTitle: {
    fontSize: 20,
    fontFamily: "Nunito_600SemiBold",
    color: "#1C0335",
  },
  eventSubtitle: {
    fontSize: 15,
    fontFamily: "Nunito_400Regular",
    color: "#5B5569",
    marginTop: 6,
    lineHeight: 20,
  },
  picksScroll: {
    marginHorizontal: -20,
    paddingHorizontal: 20,
  },
  pickCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 16,
    marginRight: 18,
    width: 220,
    borderWidth: 1,
    borderColor: "#EDE7FF",
  },
  pickImageContainer: {
    width: 188,
    height: 146,
    borderRadius: 12,
    marginBottom: 16,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  pickName: {
    fontSize: 20,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
    marginBottom: 4,
  },
  pickSubtitle: {
    fontSize: 14,
    fontFamily: "Nunito_400Regular",
    color: "#6B6583",
    marginBottom: 12,
  },
  pickPriceRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  pickPrice: {
    fontSize: 16,
    fontFamily: "Nunito_900Black",
    color: "#1F2937",
  },
  inspirationCard: {
    flexDirection: "row",
    backgroundColor: "#F4F1FF",
    borderRadius: 20,
    padding: 18,
    marginBottom: 18,
  },
  inspirationImageContainer: {
    width: 148,
    height: 148,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 16,
  },
  inspirationContent: {
    flex: 1,
    justifyContent: "space-between",
  },
  inspirationTitle: {
    fontSize: 20,
    fontFamily: "Nunito_700Bold",
    color: "#1C0335",
    marginBottom: 8,
  },
  inspirationSubtitle: {
    fontSize: 15,
    fontFamily: "Nunito_400Regular",
    color: "#5B5569",
    lineHeight: 22,
  },
  aiSection: {
    backgroundColor: "#330065",
    paddingHorizontal: 24,
    paddingVertical: 36,
    borderRadius: 28,
    marginHorizontal: 20,
    marginTop: 32,
  },
  aiHeader: {
    alignItems: "flex-start",
    marginBottom: 12,
  },
  aiButton: {
    backgroundColor: "#03FFEE",
    color: "#330065",
    fontSize: 11,
    fontFamily: "Nunito_700Bold",
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 16,
  },
  aiTitle: {
    fontSize: 40,
    fontFamily: "Nunito_700Bold",
    color: "#FFFFFF",
    marginBottom: 12,
  },
  aiDescription: {
    fontSize: 16,
    fontFamily: "Nunito_400Regular",
    color: "#FFFFFF",
    lineHeight: 22,
    marginBottom: 24,
    maxWidth: "80%",
  },
  aiChatButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.18)",
  },
  robotImage: {
    width: 340,
    height: 260,
  },
  aiLogo: {
    backgroundColor: "#4C1D95",
    borderRadius: 15,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginTop: 10,
  },
  aiLogoText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontFamily: "Nunito_700Bold",
  },
});
