import { StyleSheet } from "react-native";

const PRIMARY_PURPLE = "#330065";
const SECONDARY_PURPLE = "#4B0082";
const ACCENT_TEAL = "#03FFEE";

export const profileSetupStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  desktopWrapper: {
    flexGrow: 1,
    paddingHorizontal: 48,
    paddingVertical: 56,
    alignItems: "center",
  },
  desktopCard: {
    width: "100%",
    maxWidth: 1200,
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderRadius: 32,
    padding: 40,
    shadowColor: "#1C0335",
    shadowOpacity: 0.08,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
    gap: 40,
  },
  desktopSidebar: {
    width: 240,
    borderRightWidth: 1,
    borderColor: "#E6DEF4",
    paddingRight: 32,
  },
  sidebarTitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 28,
    color: "#1C0335",
    marginBottom: 12,
  },
  sidebarSubtitle: {
    fontFamily: "Nunito_400Regular",
    fontSize: 14,
    lineHeight: 20,
    color: "#4B3F66",
    marginBottom: 32,
  },
  stepItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  stepBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#D4CAE9",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
    backgroundColor: "#F5F1FF",
  },
  stepBadgeCurrent: {
    borderColor: SECONDARY_PURPLE,
    backgroundColor: SECONDARY_PURPLE,
  },
  stepBadgeComplete: {
    borderColor: ACCENT_TEAL,
    backgroundColor: ACCENT_TEAL,
  },
  stepBadgeText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 14,
    color: "#4B3F66",
  },
  stepBadgeTextActive: {
    color: "#FFFFFF",
  },
  stepLabel: {
    fontFamily: "Nunito_500Medium",
    fontSize: 15,
    color: "#6A5A89",
  },
  stepLabelActive: {
    color: "#1C0335",
  },
  desktopContent: {
    flex: 1,
  },
  desktopStepContainer: {
    marginTop: 24,
    gap: 32,
  },
  desktopTopBar: {
    alignItems: "flex-end",
  },
  skipButton: {
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#6840D3",
  },
  skipButtonText: {
    fontFamily: "Nunito_600SemiBold",
    color: "#6840D3",
  },
  desktopHeadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 24,
    marginTop: 28,
    marginBottom: 32,
  },
  avatarCircle: {
    width: 104,
    height: 104,
    borderRadius: 52,
    backgroundColor: PRIMARY_PURPLE,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: 52,
  },
  avatarInitials: {
    fontFamily: "Nunito_700Bold",
    fontSize: 32,
    color: "#FFFFFF",
  },
  uploadButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: "#EFE9FF",
    borderRadius: 12,
  },
  uploadButtonDisabled: {
    opacity: 0.65,
  },
  uploadButtonText: {
    fontFamily: "Nunito_600SemiBold",
    color: SECONDARY_PURPLE,
  },
  desktopFormRow: {
    flexDirection: "row",
    gap: 24,
    marginBottom: 24,
  },
  desktopField: {
    flex: 1,
  },
  fieldLabel: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 14,
    color: "#4B3F66",
    marginBottom: 8,
  },
  desktopInput: {
    height: 52,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#DDD7E4",
    paddingHorizontal: 16,
    fontFamily: "Nunito_500Medium",
    fontSize: 16,
    color: "#1C0335",
    backgroundColor: "#FBFAFF",
  },
  inlineFieldRow: {
    flexDirection: "row",
    gap: 12,
    overflow: "visible",
  },
  countryCodeBox: {
    width: 140,
  },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  switchLabel: {
    flex: 1,
    fontFamily: "Nunito_500Medium",
    fontSize: 14,
    color: "#4B3F66",
  },
  desktopDivider: {
    height: 1,
    backgroundColor: "#E7E0F3",
    marginVertical: 28,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: "#E7E0F3",
    marginVertical: 24,
  },
  desktopActions: {
    marginTop: 32,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 16,
  },
  primaryButton: {
    height: 56,
    borderRadius: 16,
    backgroundColor: PRIMARY_PURPLE,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  primaryButtonDisabled: {
    opacity: 0.75,
  },
  primaryButtonText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
    color: "#FFFFFF",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  secondaryButton: {
    height: 56,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: PRIMARY_PURPLE,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
    backgroundColor: "#FFFFFF",
  },
  secondaryButtonMobile: {
    flex: 1,
  },
  secondaryButtonDisabled: {
    opacity: 0.75,
  },
  secondaryButtonText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
    color: PRIMARY_PURPLE,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  errorBox: {
    borderRadius: 14,
    backgroundColor: "#FCE8E6",
    borderWidth: 1.5,
    borderColor: "#F5B5AF",
    padding: 16,
    marginTop: 12,
    marginBottom: 20,
  },
  errorText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 14,
    color: "#A42222",
  },
  mobileScroll: {
    paddingHorizontal: 20,
    paddingVertical: 32,
    gap: 20,
  },
  mobileContainer: {
    flex: 1,
  },
  mobileHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  mobileBackButton: {
    paddingVertical: 4,
    paddingHorizontal: 0,
  },
  mobileBackText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 15,
    color: PRIMARY_PURPLE,
  },
  mobileStepIndicator: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 14,
    color: "#6A5A89",
    marginBottom: 4,
  },
  mobileStepLabel: {
    fontFamily: "Nunito_700Bold",
    fontSize: 24,
    color: "#1C0335",
    marginBottom: 20,
  },
  mobileHeading: {
    fontFamily: "Nunito_700Bold",
    fontSize: 28,
    color: "#1C0335",
  },
  mobileSubheading: {
    fontFamily: "Nunito_400Regular",
    fontSize: 15,
    color: "#4B3F66",
    marginBottom: 12,
  },
  mobileCard: {
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    padding: 20,
    shadowColor: "#1C0335",
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
    gap: 16,
  },
  mobileAvatarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
  },
  mobileFieldBlock: {
    gap: 8,
  },
  mobileInput: {
    height: 52,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#DDD7E4",
    paddingHorizontal: 16,
    fontFamily: "Nunito_500Medium",
    fontSize: 16,
    color: "#1C0335",
    backgroundColor: "#FBFAFF",
  },
  sectionTitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 18,
    color: "#1C0335",
  },
  sectionSubtitle: {
    fontFamily: "Nunito_400Regular",
    fontSize: 14,
    color: "#4B3F66",
  },
  personaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    marginTop: 16,
  },
  personaStack: {
    gap: 12,
  },
  personaTile: {
    flex: 1,
    minWidth: 220,
    borderWidth: 1.5,
    borderColor: "#E5DFF5",
    borderRadius: 16,
    padding: 18,
    backgroundColor: "#FBF9FF",
  },
  personaTileActive: {
    borderColor: PRIMARY_PURPLE,
    backgroundColor: "#F0E7FF",
  },
  personaTitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 17,
    color: "#2A0E59",
    marginBottom: 6,
  },
  personaTitleActive: {
    color: PRIMARY_PURPLE,
  },
  personaDescription: {
    fontFamily: "Nunito_400Regular",
    fontSize: 14,
    color: "#4B3F66",
  },
  personaDescriptionActive: {
    color: "#2F1D63",
  },
  chipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 18,
  },
  chip: {
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: "#E5DFF5",
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: "#FBF9FF",
  },
  chipActive: {
    borderColor: ACCENT_TEAL,
    backgroundColor: "#E6FFFB",
  },
  chipText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 14,
    color: "#4B3F66",
  },
  chipTextActive: {
    color: "#0F766E",
  },
  mobileActions: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 12,
    marginTop: 28,
  },
  mobileSkipLink: {
    alignItems: "center",
    paddingVertical: 20,
  },
  mobileSkipText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 15,
    color: SECONDARY_PURPLE,
  },
  desktopStepCard: {
    borderRadius: 28,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5DFF5",
    padding: 32,
    gap: 20,
  },
  preferenceTileWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    marginTop: 18,
  },
  preferenceTileWrapMobile: {
    flexDirection: "column",
  },
  preferenceTile: {
    flex: 1,
    minWidth: 240,
    borderWidth: 1.5,
    borderColor: "#E5DFF5",
    borderRadius: 20,
    padding: 20,
    backgroundColor: "#FBF9FF",
  },
  preferenceTileMobile: {
    width: "100%",
  },
  preferenceTileActive: {
    borderColor: SECONDARY_PURPLE,
    backgroundColor: "#EFE9FF",
  },
  preferenceTileTitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
    color: "#2A0E59",
    marginBottom: 8,
  },
  preferenceTileTitleActive: {
    color: SECONDARY_PURPLE,
  },
  preferenceTileCopy: {
    fontFamily: "Nunito_400Regular",
    fontSize: 13,
    color: "#4B3F66",
    lineHeight: 18,
  },
  preferenceTileCopyActive: {
    color: "#311663",
  },
  preferencePillsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 18,
  },
  preferencePill: {
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: "#E5DFF5",
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: "#FBF9FF",
  },
  preferencePillActive: {
    borderColor: SECONDARY_PURPLE,
    backgroundColor: "#EFE9FF",
  },
  preferencePillText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 14,
    color: "#4B3F66",
  },
  preferencePillTextActive: {
    color: SECONDARY_PURPLE,
  },
  storeInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 16,
  },
  storeInput: {
    flex: 1,
  },
  addStoreButton: {
    height: 48,
    paddingHorizontal: 24,
    borderRadius: 14,
    backgroundColor: SECONDARY_PURPLE,
    alignItems: "center",
    justifyContent: "center",
  },
  addStoreButtonDisabled: {
    opacity: 0.5,
  },
  addStoreButtonText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 14,
    color: "#FFFFFF",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  selectedStoresWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 20,
  },
  selectedStoreChip: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: "#EFE9FF",
  },
  selectedStoreText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 13,
    color: SECONDARY_PURPLE,
  },
  preferenceToggleBlock: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 18,
    paddingVertical: 12,
  },
  preferenceToggleCopy: {
    flex: 1,
    gap: 4,
  },
  preferenceToggleTitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
    color: "#1C0335",
  },
  preferenceToggleSubtitle: {
    fontFamily: "Nunito_400Regular",
    fontSize: 13,
    color: "#4B3F66",
    lineHeight: 18,
  },
  preferenceSummaryBox: {
    marginTop: 24,
    padding: 20,
    borderRadius: 20,
    backgroundColor: "#F5F1FF",
    borderWidth: 1,
    borderColor: "#E5DFF5",
    gap: 8,
  },
  preferenceSummaryTitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
    color: "#1C0335",
  },
  preferenceSummaryText: {
    fontFamily: "Nunito_400Regular",
    fontSize: 13,
    color: "#4B3F66",
    lineHeight: 18,
  },
  inputPressable: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  inputValue: {
    fontFamily: "Nunito_500Medium",
    fontSize: 16,
    color: "#1C0335",
  },
  inputPlaceholder: {
    fontFamily: "Nunito_500Medium",
    fontSize: 16,
    color: "rgba(28, 3, 53, 0.35)",
  },
  fieldDropdownActive: {
    zIndex: 1000,
    position: "relative",
    elevation: 16,
  },
  dropdown: {
    position: "absolute",
    top: 60,
    left: 0,
    width: 140,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E4DBF6",
    shadowColor: "#2A174C",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 20,
    zIndex: 1001,
    maxHeight: 300,
    overflow: "hidden",
  },
  dropdownItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  dropdownItemText: {
    fontFamily: "Nunito_500Medium",
    fontSize: 15,
    color: "#1C0335",
  },
  webSelectWrapper: {
    width: "100%",
  },
  webSelect: {
    width: "100%",
    height: 52,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#DDD7E4",
    paddingHorizontal: 16,
    fontFamily: "Nunito_500Medium",
    fontSize: 16,
    color: "#1C0335",
    backgroundColor: "#FBFAFF",
    outline: "none",
  },
  webDatePicker: {
    position: "absolute",
    top: 60,
    left: 0,
    right: 0,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E4DBF6",
    shadowColor: "#2A174C",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
    zIndex: 3200,
    padding: 16,
    gap: 12,
  },
  webDateActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
  },
  webDateAction: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#EFE5FF",
  },
  webDateActionText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 13,
    color: "#4B0082",
  },
});

