import { StyleSheet } from "react-native";

const selectProfileStyles = StyleSheet.create({
  desktopSafeArea: {
    flex: 1,
    backgroundColor: "#F8F5FF",
  },
  desktopWrapper: {
    flex: 1,
    flexDirection: "row",
  },
  desktopSidebar: {
    width: 320,
    paddingVertical: 48,
    paddingHorizontal: 36,
    borderRightWidth: 1,
    borderRightColor: "#E7DCF6",
    backgroundColor: "#FBF8FF",
  },
  desktopBackRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 24,
  },
  desktopBackText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 16,
    color: "#4B0082",
  },
  desktopSidebarTitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 30,
    color: "#330065",
    marginBottom: 12,
  },
  desktopSidebarSubtitle: {
    fontFamily: "Nunito_400Regular",
    fontSize: 16,
    color: "#4A3B66",
    lineHeight: 24,
    marginBottom: 32,
  },
  desktopStepList: {
    gap: 24,
  },
  desktopStepItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 16,
  },
  desktopStepIndicator: {
    alignItems: "center",
  },
  desktopStepCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  desktopStepCircleActive: {
    borderColor: "#4B0082",
    backgroundColor: "#F3E9FF",
  },
  desktopStepCircleInactive: {
    borderColor: "#D7CBF2",
    backgroundColor: "#FFFFFF",
  },
  desktopStepNumber: {
    fontFamily: "Nunito_700Bold",
    fontSize: 18,
  },
  desktopStepNumberActive: {
    color: "#4B0082",
  },
  desktopStepNumberInactive: {
    color: "#8E8EA9",
  },
  desktopStepConnector: {
    width: 2,
    height: 44,
    backgroundColor: "#E7DCF6",
    marginTop: 4,
  },
  desktopStepLabel: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 18,
  },
  desktopStepLabelActive: {
    color: "#330065",
  },
  desktopStepLabelInactive: {
    color: "#8E8EA9",
  },
  desktopContent: {
    flex: 1,
    paddingHorizontal: 64,
    paddingVertical: 56,
  },
  desktopScrollContent: {
    gap: 28,
    paddingBottom: 40,
  },
  desktopHeading: {
    fontFamily: "Nunito_700Bold",
    fontSize: 32,
    color: "#330065",
  },
  desktopSubheading: {
    fontFamily: "Nunito_400Regular",
    fontSize: 18,
    color: "#4A3B66",
    lineHeight: 26,
    maxWidth: 560,
  },
  loadingWrapper: {
    paddingVertical: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  desktopGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 24,
  },
  desktopCard: {
    width: 220,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#E3DAF6",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 28,
    gap: 16,
  },
  desktopCardSelected: {
    borderColor: "#4B0082",
    backgroundColor: "#F3E9FF",
    shadowColor: "#330065",
    shadowOpacity: 0.15,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 6,
  },
  desktopAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#EFE5FF",
    alignItems: "center",
    justifyContent: "center",
  },
  desktopInitials: {
    fontFamily: "Nunito_700Bold",
    fontSize: 24,
    color: "#4B0082",
  },
  desktopName: {
    fontFamily: "Nunito_700Bold",
    fontSize: 18,
    color: "#1C0335",
  },
  desktopSelectedLabel: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 13,
    color: "#4B0082",
  },
  desktopAddCard: {
    width: 220,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#E3DAF6",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 28,
    gap: 16,
  },
  desktopAddIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#F2E9FF",
    alignItems: "center",
    justifyContent: "center",
  },
  desktopAddText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 18,
    color: "#4B0082",
  },
  desktopEmpty: {
    padding: 28,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E3DAF6",
    backgroundColor: "#FFFFFF",
    gap: 8,
  },
  emptyHeading: {
    fontFamily: "Nunito_700Bold",
    fontSize: 20,
    color: "#1C0335",
  },
  emptyBody: {
    fontFamily: "Nunito_400Regular",
    fontSize: 14,
    color: "#4A3B66",
    lineHeight: 20,
  },
  desktopFooterActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 16,
  },
  desktopSecondaryButton: {
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#4B0082",
    backgroundColor: "#FFFFFF",
  },
  desktopSecondaryButtonText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 16,
    color: "#4B0082",
  },
  desktopPrimaryButton: {
    paddingVertical: 16,
    paddingHorizontal: 36,
    borderRadius: 12,
    backgroundColor: "#4B0082",
  },
  desktopPrimaryButtonDisabled: {
    backgroundColor: "#CDB8EC",
  },
  desktopPrimaryButtonText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
    color: "#FFFFFF",
  },
  mobileContainer: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  mobileHeaderGradient: {
    paddingBottom: 16,
  },
  mobileHeaderContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  mobileBackButton: {
    padding: 4,
  },
  mobileHeaderTitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 24,
    color: "#FFFFFF",
  },
  mobileBody: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 24,
  },
  mobileHeading: {
    fontFamily: "Nunito_700Bold",
    fontSize: 24,
    color: "#1C0335",
  },
  mobileSubheading: {
    fontFamily: "Nunito_400Regular",
    fontSize: 14,
    color: "#4A3B66",
    marginTop: 6,
    marginBottom: 20,
  },
  mobileScrollContent: {
    paddingBottom: 24,
    gap: 16,
  },
  mobileCardsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
  },
  mobileCard: {
    width: "47%",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#E5DFF5",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 24,
    gap: 12,
  },
  mobileCardSelected: {
    borderColor: "#4B0082",
    backgroundColor: "#F3E9FF",
  },
  mobileAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#EFE5FF",
    alignItems: "center",
    justifyContent: "center",
  },
  mobileInitials: {
    fontFamily: "Nunito_700Bold",
    fontSize: 18,
    color: "#4B0082",
  },
  mobileName: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 16,
    color: "#1C0335",
  },
  mobileEmpty: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5DFF5",
    backgroundColor: "#FFFFFF",
    padding: 20,
    gap: 6,
  },
  mobileAddCard: {
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#E5DFF5",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 24,
    gap: 12,
  },
  mobileAddIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#F2E9FF",
    alignItems: "center",
    justifyContent: "center",
  },
  mobileAddText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
    color: "#4B0082",
  },
  mobileBottomSpacer: {
    height: 32,
  },
  mobileFooterSafeArea: {
    backgroundColor: "#FFFFFF",
  },
  mobileFooter: {
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  mobileContinueButton: {
    height: 56,
    borderRadius: 12,
    backgroundColor: "#4B0082",
    alignItems: "center",
    justifyContent: "center",
  },
  mobileContinueButtonDisabled: {
    backgroundColor: "#CDB8EC",
  },
  mobileContinueText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
    color: "#FFFFFF",
  },
  desktopModalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
    backgroundColor: "rgba(15, 6, 30, 0.45)",
  },
  mobileModalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  desktopModalCard: {
    width: "100%",
    maxWidth: 640,
    borderRadius: 28,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 32,
    paddingVertical: 32,
    shadowColor: "#12062B",
    shadowOpacity: 0.18,
    shadowRadius: 32,
    shadowOffset: { width: 0, height: 18 },
    elevation: 12,
  },
  modalSheet: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 12,
  },
  desktopModalScroll: {
    gap: 20,
    paddingBottom: 16,
  },
  mobileModalScroll: {
    gap: 20,
    paddingBottom: 24,
  },
  modalTitleDesktop: {
    fontFamily: "Nunito_700Bold",
    fontSize: 26,
    color: "#1C0335",
  },
  modalTitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 22,
    color: "#1C0335",
  },
  modalSubtitleDesktop: {
    fontFamily: "Nunito_400Regular",
    fontSize: 16,
    color: "#4A3B66",
    lineHeight: 24,
  },
  modalSubtitle: {
    fontFamily: "Nunito_400Regular",
    fontSize: 14,
    color: "#4A3B66",
    lineHeight: 20,
  },
  fieldRow: {
    gap: 16,
  },
  fieldRowDesktop: {
    flexDirection: "row",
  },
  field: {
    flex: 1,
    gap: 8,
    position: "relative",
  },
  fieldHalf: {
    flex: 1,
  },
  fieldLabel: {
    fontFamily: "Nunito_500Medium",
    fontSize: 13,
    color: "#6F5F8F",
  },
  input: {
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E0EC",
    paddingHorizontal: 16,
    fontFamily: "Nunito_500Medium",
    fontSize: 15,
    color: "#1C0335",
    backgroundColor: "#FFFFFF",
  },
  inputDesktop: {
    height: 54,
  },
  inputPressable: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  inputValue: {
    fontFamily: "Nunito_500Medium",
    fontSize: 15,
    color: "#1C0335",
  },
  inputPlaceholder: {
    fontFamily: "Nunito_500Medium",
    fontSize: 15,
    color: "#B1A6C4",
  },
  fieldDropdownActive: {
    zIndex: 10,
  },
  dropdown: {
    position: "absolute",
    top: 60,
    left: 0,
    right: 0,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E4DBF6",
    shadowColor: "#2A174C",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  dropdownItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  dropdownItemText: {
    fontFamily: "Nunito_500Medium",
    fontSize: 15,
    color: "#1C0335",
  },
  phoneRow: {
    flexDirection: "row",
    gap: 10,
  },
  countryInput: {
    width: 96,
  },
  phoneInput: {
    flex: 1,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
  },
  toggleTexts: {
    flex: 1,
    marginRight: 16,
    gap: 4,
  },
  toggleTitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 15,
    color: "#1C0335",
  },
  toggleSubtitle: {
    fontFamily: "Nunito_400Regular",
    fontSize: 12,
    color: "#8E8E93",
  },
  errorText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 14,
    color: "#D34053",
  },
  successText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 14,
    color: "#1D9A6C",
  },
  modalButtonRow: {
    flexDirection: "column",
    gap: 12,
    marginTop: 8,
  },
  modalButtonRowDesktop: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 16,
  },
  secondaryButton: {
    height: 52,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#4B0082",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    backgroundColor: "#FFFFFF",
  },
  secondaryButtonText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 15,
    color: "#4B0082",
  },
  primaryButton: {
    height: 52,
    borderRadius: 12,
    backgroundColor: "#4B0082",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  primaryButtonText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
    color: "#FFFFFF",
  },
  ghostButton: {
    height: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#4B0082",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  ghostButtonText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 15,
    color: "#4B0082",
  },
  buttonDisabled: {
    opacity: 0.7,
  },
});

export default selectProfileStyles;